---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: "{{ .Values.global.images.prowlarr.repository }}:{{ .Values.global.images.prowlarr.tag }}"
          ports:
            - containerPort: 9696
              name: http
          livenessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: PUID
              value: "{{ .Values.global.storage.uid }}"
            - name: PGID
              value: "{{ .Values.global.storage.gid }}"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: prowlarr
  ports:
    - port: 80
      targetPort: 9696
      name: http

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
