---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: >-
            {{ .Values.global.images.radarr.repository }}:{{ .Values.global.images.radarr.tag }}
          ports:
            - containerPort: 7878
              name: http
          livenessProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: PUID
              value: "{{ .Values.global.storage.uid }}"
            - name: PGID
              value: "{{ .Values.global.storage.gid }}"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
        - name: exportarr
          image: >-
            {{ .Values.global.images.exportarr.repository }}:{{ .Values.global.images.exportarr.tag }}
          args: ["radarr"]
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://127.0.0.1:7878"
            - name: CONFIG
              value: /config/config.xml
            - name: LOG_LEVEL
              value: info
          ports:
            - containerPort: 9707
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: media
          hostPath:
            path: /data
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  ports:
    - port: 80
      targetPort: 7878
      name: http
    - port: 9707
      targetPort: 9707
      name: metrics

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
