---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  recyclarr.yml: |-
{{ .Files.Get "files/recyclarr/recyclarr.yml" | indent 4 }}
