---
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secrets
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  RADARR_API_KEY: bootstrapplaceholder1234
  SONARR_API_KEY: bootstrapplaceholder1234
  BAZARR_API_KEY: bootstrapplaceholder1234
  SABNZBD_API_KEY: bootstrapplaceholder1234
  secrets.yml: |-
    radarr_main_base_url: http://radarr.media.svc.cluster.local
    radarr_main_api_key: bootstrapplaceholder1234
    sonarr_main_base_url: http://sonarr.media.svc.cluster.local
    sonarr_main_api_key: bootstrapplaceholder1234
