---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-sso-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCs0FseDaerzEqfC/BXNKIwYppYYN7NAMpUrNqLqVEKwb5jkFiShb8StQanRMunv8B/EWlEey+vEEAevTbNoKu4e+0qONaeLhPt4amqJ95ia7bA1mKhXKqkWK4dRtihlFa7ZRYhHbshxn4vsAFBLNlzzCM8kOcfHLp3EIsmM3DDMvmLcYu7HnAuT5GW+f8LM6fFimerrZbRarQB0tlm5hh6153PyCOOvS26UfYYiop7lSknnvuA6rOWfIeqLWX2w83jUEAqmnI4V494HTjgfHq13htYmdg9Mnf2jJv+K9JlYej3mf4C6lZSDUUO+BwuxobTCCXCbaWmg1lteS2WMcAJRVXycrZPtDG3UZ77+ZUeHzsKN8g/8Djz0GmOicWAeML0ss2f5A0TVBkfs1NzteOs8e/eUBkgCb/+HNnbKiGnfkJxfTv24DUsT2q1P2dDgWJe3+4S4t0GE0N/vkio8xIbZcwYqFrMAfAzsBiqkzBxsa9KEyITR/NvGGPF/D4k/5xQJTbHI7rb3kNw/j/AA3ljqZ0WFhbbXwkrkle1YPvSSW7X7aPsC5wEQ9ljdT/gstXE9fOTOLWZyReRnDr/V+4bpQD3jwWu4NovQxiYxcFEZyLfLe0bIaZSiAGc8eB+bS10orMez49vqyqCZqPiGTv8fzn2+hWBnD9m7qtCXRO3/57HACKTBZT5NugL22TEygGoooJOzdGmdgrCHsZ+q5/sOw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-sso-secret
      namespace: argocd