---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authelia.clientSecret: AgDIIjB9BixGxZ857qAYdySgBc1PEu1+q23H08b6fejDxhr7pOQz54kk9yF/MsCwmHW1r7Pxm2HKxPFnKMDwGpGuAD9z3o2XdSRuWn9UVCf7uv0e1EDQVAenScwqcM49LJEt4n6+ATsBL+Q0No1BG/ekgQfjXajLlPDa4AeYZfQYh31yZiCFyuJcEEIj8i5Y4eqcx/oIl5DZsYxXys18jH0sVxlJNwyz5c+U5a8rpNihOEObkcSYprjB4tVHLc+qf5Xey5i1aLgvUedy6z4BE5eq9aVXzEvQ4Lhp/cUVU5xyY1ZIDmEe02L3zraFTyEpWsYgnm1CPqbwGKGl+WDWFjmmVln7kg7SWRgtJSmc4VS7A0GLUgjyCpv0jjncMOnOYZI34LeF3XybTife26WMxPKAUJIK/L+Zupnaccqx0qAgFwU/wi3/6tEz5D6UNkKPqzeOVMBnqREIEozQPMBzuDWM7XJtqODpw2gHuNDrdhK+6AbJM92MeZATjZwDYotXHxecvaI2/KnmHdUnCMRmm3sZQz3/0txJG4PnHtvlSSiq7VuWEtLxWqHhbBg1BPT7fJCHVhfi8WXZtq5mNc63y8MgSAYaIO+44RXwdsFcS9Y4HW9tFcXwNDcimnxOJ+ay7ysYutM/WOK0py7pp6++u3ShLvXpn2HiYcPGPg4o2CTFKCMxaCqkTdRyaxEDiEUbI1v0FWNv5t054fWKHrAdvB2wew==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
