---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    ntfy-webhook-url: AgB3CQgWtIlcGjwwMikYFp8Fifw4SrB+h9k5jbrpBiXOo8GmvwThxCgUsBXoH0a/MUwtgjff4mdNuL8mYdq3ga7uSIPIfgvBc0AYxwBmXSrScg6cG74gwv+tILM/WLVIp0B3YsHYgQGkFXrX+0S3mqX/r8YYfHaqQxLNVc1vj43w8pqOc1pQEjIxG+mo03iAkp843dW5AOIBtB1sIvPvUpwOSghklHT/42ryOdMjx590M1ZMscFmBsUwThRwUuWTGRlprsf8CeS1819R7tscX8WoW9ahA0hFnR9QCvYT0soh2rrcIILTZUmFcpWc5/z06/Yo9eXkxJBRsM1JsmwH0/k91P6pjn/drg8EpXQJ7hfqP/s0aadQmP+QidL2LySwew+tc3Lf96yIH8+F78Kq+JpLcJBAcUpHz/2DQpcJ6wYHjh8Of/NlITDi0sn/aTtOxBz6zN2oOFqkgdyHt41Aalvtu74e8/7i3WCBD54rE86G0ASBk3UH+irE4in9WWqO7/BoqCly4EeBnYqIujTM4UXvf6RC/S+bz+1HtFyXK2CGFLWtLgP6ftSL9KXO+qMGXGoVC7bEXgK+Z6L6vcKS/XjkdC0AsUBsw8d8jqoVtqQuq9mvMCo7oQbW++llLy1SsuQFfYdmMBkzR4mAdIC+BU4ElGzQESjiScpbclB6s/ASFkzFnFl09IvmXYR1Z2wj6rwiVqaNv2SNcPwjbNeL2BQeywG6gBCjM4a5LREZlp53IklLHz7p6fwzPs0B9DoEQNNg
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
