---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    client_secret: AgCannm1sp0Stu7beqnj1vhgJ/JJcualJ5ZKkz5eGwo4T5kVN7LC48ahpHlgJk1CooRo9Im+yN8WyF1ygNNbBaVXp+PmRb0qPOZTtaTpCLtcHgyE8L05vmbGMJb7HuiKSgEjwXvsdvj5m6AELGspmft0e0k1Rjee0gjPbnTBLotbu/xPTeBm2OcJ2rgT/239TtASnPGxb+aWewKCgyhUzWcpWakNIpCmL0ttaXuC37L7M7bYmK8QfNkhSV26K9Y0Dc79IHJtMZzjWR67PEW+c9cRKj7ZYpMCMOh/uaUWvM/Z+cSViqQvPMbCgaPzCO9PWUYW4JzQmEO70ytXth0uupPkrWnPANYPleOLzAL2QYQ5IPi8OsXq94DxRbDIR1P/xQJUCsmGLYvlOYDtIQqD963xd5Wc+phZqDc5hB/uvHpaXgpffv+WpGDsDRd8k9ZA2EWRKXyfvMwa4C2C5D2uFsUwIM0fncNmPDp7Lznxo+AhdqCXNGKl33UTM5VriLZixbrck4xZzz6URVZC/Nj03NlvPsdVAVa8fKbipMRbcxKRk67O3RaRvy7A6Gr2RVci5b/uwuGqJU94s1W8KtRyRmZJEbXgD0H45G4s0pbl578zrKwVK29rHpKJ+5N5bkuZDKcOfesDWCeWtz7CQpABaBtts35QnEirOcjf4Gn7KrGW+jG0g1L15WtqyhNYeKmPt8b8VGY9fHHs4bGxb9qZmNTwRQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-oidc-secret
      namespace: argocd