---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-notifications-custom-secret
  namespace: argocd
spec:
  encryptedData:
    ntfy-webhook-url: AgAU0NovRjoEHHJ5bvoTnZ96XnxjLDDJo87iQIMqDT/k8koTpvJ2VRsj3pIXwaP+rwLysUpoM5L8EqiTPyUc+MnEZtcPjOvXsg4RsxO24aB5yweWAB2XB8vkNuPqZUwjz0EXLM0bCmY87kLVkxCVjF1QXvTcScu2aE/jFNgsQLP8hsl2+/+Kd5xC+T/uA06oSG4vjAElMPd4irw5+ZLDY/fkQWi1SsqdcKpS3nyr78CUIpT6DOVjzwcAQMYjrVb7pZe41t+mzvWi2iKTbqdLEPzA8hdNX8ds/aVvDtV2wivdmdu7B5bm1kPrCVJfZ2+93/fNk1sTnvFIlnkTsBhPTdhBVwXmlfOZ4q75RC/W7BivL0YU0U15USlBMycBXnmyiX7p0x20aWDsSCke8THoRiJKZNMvAV0uoloZ7//l7oc3KO1iNOe/KEmC6pfzwMDCOnZQFNbtBBKia8zKwS4jodq53U/x+I1rAY41x+G7hwW05J/LC9N1SBJxa2sG/P79aiI+nP57YGl0hpWCtDOXk0m8TPPM3rsPJ8S1As/k5tIM7XbJ5MiwIMdpO2LbcbjHGy2rX5t3PXbnre7MUqNa9BuMAJIrYdPHjwtWA+Q6irx2Wu0Cqn5x/JIuRwQfR9ai6VUhxTWTCT3qRqTGWVnVKP2Zp8rtkkigkjcXCgauCoQkB9bPOyxsURE8/L7nK89REqhIjDf6Bo0giHJ31A0oowlFrnOrj82ATNXNqUX5LkhriGb/JlcD6LEjfglib0Y0R5TJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-notifications-custom-secret
      namespace: argocd