---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-sso-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBj8fwSUYCqZsKDB1up8ZEEKzTyoUgyLxabW56yOSY2GaeTfB+Ceok0k3fuKDStYJZKg3X4cFWWBgMuUwLXAkDO6H3NXjcAa9ZOETbdrjFphx5PHCz2UqX2o5otwfOp3fxruijd3FXKbcWrTmU7UaAjke9Mhcjnx7W/0PQ5EaS092O3WelzDW6KtbRnHSI3fAz5/6kTZ9JDl7qSDDOcitGxjWasAVi8W4FHUewQMk/07WR6pO8L5JLq91Te0o/ZVAd5vium24hcnjWxcjH1Zmlh13fru9HpYzJjFZr700YBHLIXsZYRmk5xPoceqvkilTJ5XB2hwoAyo4jTBwSt0sLY7VnUAqzNiSz782jmk2xp6TrIxfsbsZrSnztv8zRVJKsGYAVvdnnDTDKtNq5sT85yXNZbcIUUwV0Mkq5/jktYtyrdpAzPBq+mpiux/cVvBQ4rrTSEdPBn6UR5Zvcp8phVWOMRrUrbrO1Y3E6L8gOMmdmp0RaSbuPNdRNGUmcWmlgjKHGSagmqxGNc/e/P3SOBGKRfRzXZKxhAX2Nbst10BgoR1A/7QHSw0AJUguBXKnR7xPntIPdc41JlJMTplkXZmm9ljdTN2yIn0y74B85xhlMr4rdRd2uXhyVFwiHKqdDAkFlBGHB+KHw2+oiZZ/BM0ABNKDO+SyF30xMp5dQ+BzFPxoUtY/ykZQEXpZGxHCGpGX7zKh7lF6P1s6PxBvfyzA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-sso-secret
      namespace: argocd