---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-custom-secret
  namespace: argocd
spec:
  encryptedData:
    ntfy-webhook-url: AgCl3lnGWFm8nbNqgS6kams7O8IY+NNeKa1V2HKu8D3nDKIcP8Ev/b57LjyhNdNXWPO/7scjZ7wLrObtm62/f+GLcA9fhU/iXXiX6lkZOUlWTT8tKaiunPS26XwibY5WZoO/LvpLoRTKUxuTMhXo6IQGncqpvwdHMljGDqPpnGdEsHrHjWvjDiXLxbaUFS671KRFhN/W9vUDKC6VC4G3zcVmert6nF9vqng0Oks9jL0GFtgWOSjvASKuyKXKEu+utko+TXCUSeu20vAeiI1TyyvPV291+Sdgio9nr0rOlNGN9nmnvwSDnCd9Gp6Z3ALabUzkny1iYMLaSJSYUskWm8fBhADkUFAg/NX9BBdnGAKbobQ1n/afuZ/HpsxXTTbauoIt89+I/BcqhY8oH2laQvJhNpkSAgpCtPQ2kN8we7chcFYVwvFjE/0sZGL3s1eKaVXSaezY8QXwOUBqDzspQ54ANjl34iBcb1d+pmplHji0cDKNLh2IgjtzFoDQhl9rYZtwgvmV0UuFmXomtFdepTXj0dEVc4GcgMbojzt/igZO5V5hq+W5rzQj6IGKEQV8PgBnPDIaWP8IfVayuR0ZMt4z5MWV/m82A8w5fDVOc47DE0WO9mRcnhFeTDXUFhW9VYDArnQwirKyOM20lHizWjU5srjLdCQ2gziHo9hbixG2koLdhf4fa9Rop96wH+Xc8xrmKcbn+bh0QN3QX9ZLaQpBiGwbKE/GIsZ5tCPyQp+u0HgXlhiY3pDyDBTBimTHDP4I
  template:
    metadata:
      name: argocd-notifications-custom-secret
      namespace: argocd
    type: Opaque