---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-sso-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAmavKdN+Yqv5cKbAfbN0pWkUgGNbsZn+jN6FUQnNLzwPOCB+uct9MvQCvomLgQe5fNPTat03II+Fj9Ce3YSqvSWV+VhBjyCMXLUwKE5h/5cd6MWz0mdF5uY3nWlN5qxId09S5Ir19pt2MpktIcZnJDO6yxxtOAWOiSlJ6ztccA8BFoiiQ5LYTTe5X8qHzrq0qigYbfwL1Efgqc80aYLhsbirbxMNPYaMGYHH84ftqfXCRJ2pCvL3ww+D5QQxIa/KoacWwI/8uCJzFqu20SgmStjzrm1Ri1KZ/5GQWGerIv7r9eWH/WkVdXwLeVWSfNTSRDJHtSQzPUJTPOFVCCpfbKH/kOjKbWiL3PBjou8LyQNTjIpoAqDy7MHI16c29/H7ks0dtGYQlyvM+ZN6LoWPN5TIyef3rmIoZo0/40X0sf/Z5VhvT07P/uKY/wsQsrdRvJMoKmwHIuI2J9i6McCo/PGniCKuEoMjJ2rYnpve0/c1mzo6ocvaBGLGupi2yvmuU3j7uPBmXqh2ZGYarWKMfr6uVPRCDAyaZwRKyW6quyvRDNscZWmAyI4kLfX9MvI4VoldsPLDsg7yv0G+bKtiVFhnpggNcXQMdklPzM0hdFgTnI9RHRERDKe/MXHOkqUOBjrGTnaO01ghrBlahTql+6RxcSE4ln1iZT4WilGgbfjK05fvYCYzk4fH/x00W6tGAJDS5STwK8bcCme4bwdxsgDQ==
  template:
    metadata:
      name: argocd-sso-secret
      namespace: argocd
    type: Opaque