---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    client_secret: AgBsMlwxtGmu+rElNAW6Ue1KgufyUsByEbCCoG51+TjsYvtXZVVF7A90tuxX71R1dV1q+ZRXA6GCKhe9ibbLKNFh9JGqCCcdhHMZVnY4my1cmxlXPRRPZOHxhmvqKeAYQAKm7a1KPrUXP9w8dnGVjeuUMgNL5d1M7C4lsvvDUqy0k4JiGUuscYW0GZBFR1fWnq2SShplNMYyxzXp64dkA3YyXCRRimJ/LjZyh1zM/QFjXW9AioiSaeBQRZUJrGz7lLNrCMhGoHcKb3tJcrK7GQu9248IlucMfaoZC3w0MdWUtjU09YJDBCHz5+lehVgd7Isn//pzl3v8SEE27/s3TRRw3Mtojlzyhjnav94SiD44znIrKQd/ZHWT51sU+HdPW0U2ik6+3k41h2N9Ydzr8x8Zb9cNmDJSXgKAyQ1+4TmCQvDMGyTjWBw1P359s19VZudRLqN2dcMKco3HFl6GU+m1NlCHCO2N8vikLHsdrZ96C/KGdRVrQpO2C/9/EFnyWqzNIPqLhJzhEgf2G7uNlFbblo/Tg2gq03zmpG1DuEQvC/nnQp/iyWE0optZITsIEuQyUPDGfOy4oS+1tmI+F6nYrrUxs3o+FA+ua25I2gppveYir8qYjzacd/lwRI0nJyTqbO7XmLjP5B1GtE0sXSLbPXMy2s2DFbD+xZNbpQfai2C+OfQMkk7aH+tjg86a/8MtnupJ+BtH6TMzxeShci/+QA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-oidc-secret
      namespace: argocd