apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-config-files
  namespace: mgmt
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    configuration.yml: AgBXyCqgR0C2L82W9sWbYJm6XU8lY0v/FpZ6Q9mNbC6Z7f5U+eW1L3bY5N6Z7f5U+eW1L3bY5N6Z7f5U+eW1L3bY5N6Z7f5U+eW1L3bY5N6Z7f5U+eW1L3bY==
    users.yml: AgByl80qUWuDyp24VS9Obpzezjl/tZ4VNYPD87KrjK7Iaps0Lnx4/uhrAc+jiUTFUDLkm7XiqIkcXOJA68t8rQJcMMFIonHFYh4sjqbC/5nXkRnTSRqefxVI0BQQemKnwSxf+PDZ3bXj3iUsSq+/+RUmnggwQrgb28Glmsy+zP8SxmPHY1XOW8z9C5zxYpacavL1VT2lY+aTHCOiDL2e5uHXxRmwyKbusY0hFKgIRDIclhsLFvTcMtKLMREj/oKamXkjuZhsUL7uADN+/Vd5TcIFy6SIRfbc088XlL3kcC83C2sQCyidC6EUe4VKC4rGr431OCXwAuJs8PDAYhc2jAOy3dAdqu02NXv2HAHPLIoUnC2Mm/YmVY4um+g2IBvFYMXEIclVz2Rznh9LPInDpReMqYdd5hLANMLA06I0EsxMtK1Ju6FY7qB1oNuZ0izEx80SPeIM//krkdtyX5I4F7a6RazZ4F2m8PWYysWeQyaPkUFajH0qlM+akydHbSvMM2TmKJMzdshknzKdHHZcLIOWM7MZ5GZfy21Fp0ox3rPT7K8cv2TIQMrs/FGxXU4DjjkmVkvI9sAm8R2v+zQDCey77Q3/IvzlABIxhXZKHO9iaBLimmQ0wZDJupRssh31PGg6iDrEvskK0K7d8aK4h1wvnW5HkXszaNPd/Mx3q9s4ZRxX9x/PgrN6tHHBui02I6BmDgh8lGCO5fkykMiArDRtSOJuyLeFp3X27yGkIQC4cKLENluM5GwiMEEZkDVjfSnqHK38AHHLDy2QX3F++I2NwTHRgvvgMBi0Vb3K91nKPDciIAXShUsdmSDWJASiDLnISCxlvi/inJOofg7NJfsBmfHjMSCE/Jc29o0divcLnP5MJahO3kgBMFd4Y3gu5Bx+zEOMTxJNMMRB0izHR66g5KvdahG1N3jV9k3vQzuJZogFL3/z4tPGWi0tFwGs/2MPgWpaAFnm5G+tG1LYoQmk/GM0shWSIW71Uz2ae10V1crN3mMON+yk90Eu8PDjlmUPlWlgqdtvs57nog/5Mg==
  template:
    metadata:
      name: authelia-config-files
      namespace: mgmt
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
