---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAXm08jbKP0ASV2fa3frpxb3aporGefvDrRr1YaVxbH3Ccs5NS9k1X7jnSeuHoGHWy35rNKw5RSIO6oYJS8pa+Hf7wIDfB1prCvZctmNP289nGgJsghRUcfs7nuI9roFkaK4o4axIwyrLBWdQ7+5X6ydnklQs9ub9KfdIiTKlRzR/EQFuHneh9I6OrkKQt65DAcMCzpt7Cq3vZY+PCyaTbbLH3YzKUHqGFVxjPYGjdfGst+3hprmSMPewPNoTuf5J3qUgb2Zr7YZmgXloV75Xgott7dEqbZOm/RPuqg54RC/cRBWK8zptJiLQZgPZCrmWXco5Whd4x29wo45yTzt1xxPZ5olyk1bCpOCxOqf2i+2xe8SApzu5NBAmCtvwrwcsXRKNhuveZT/ZwLnbU33O38ZqgJOEuQXMuizLa+HN0MVSgNEvleC5x6m4U1qHoFO1vk84mTJIBA1zEANrTh/EwJYFiOt9wzVxXzDzSZTd6zPmAADHTxfo/XluE8Z/cL+C64064GaN9X92ZvmuWV27MTC99LL5MF2jBljYKe7OcxddNQSXEx5UdK0GQPDvRXvX6LqQju7MklGXDtEjPDIafbOr/3W/R1+dH9fZ6UbYw57wAZTp++OK0IzqgDsSRjj+U+a98knioDlP7BKbaEnsCmL1zyGVAPj8nywLkLTuVVpKH6x1nxR/oyqt1tYAFTS/lQ+td5Z5ILBxs/vYBapTSF1z8ReCh4HvBwBPT8EbceUKXwnAShPA+pWuIQXYpyyCSygciMNbUUGPNYdxYdAzdGXkVH5isNvBR19xiIl4pI4yo84IV6lQsUJCHn0jUJAV/y2S6t+vEvcYEhmH3QCwdSJ8UudSasS+LQJinWTnKTkaKdJP85KaTgp/bu1jgXyiRhbq4ZBJFi/EQ0xxj4rvLYrsntQmPvn76UIk/zm2Yt4qab92oJfIdyBTz7SJElvRMxlXRGuBDjPj6S0WVCqRxmOcDpCHtIdu3yXqxkjtkIhxGY/JLAOhu1jz85AUoWxcA=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflared
    type: Opaque