---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAF57hanurb9SeeF/OTwMpPLtGT+L8mcnyU0FYXnkEVhFhUC1Z5dQRU/FxBr2TjEzbQqXR6UBfGLKZYZOrpIz6UA04+HOghuUsmQgff/JHm9JS4R7PpxH7kYChwU5bTqVQqv1AJCMbOJ+ArK/qzB9VJR8GKBPANMSAO9IFivzEdygm8RhR5xKEfxPuhJSCoy28kCxa8nwKt/WsWXQSctEeh+6Ekru7FpaF0pl1ac54UQw4PyRv1WCj1Bk296gzlBG89byXrrY17AKtCvMr98gS3yQpdpTJ+8+y0eurB+LGRyWZRb0MdOjhUtL/8pnM9Y1yUiJG6MnjSMXL/gdGgC9cr/jmSftrnpNFBNd3A8+RvdvT5N8hahME3VpKoJcdTSQntLs5Vy2ZWEIPIFHLuBHiGp0TD6tgAfL+rd3j9csj5Lan9BytiENN6qe84jjSIZ45sLNhEwHOzsOePv44JFZChagv88HcV4ytBIZJa0zzafw+qjNspuMvGiV+cW89KNP8Khc+ocanvy1/o0Nq4JzXviu7TutF/iCsoio/+wPdN59qZXQO4KCNkTQ2kaaYRMYm4hLKCPnJLHv1s8kJdiZ9posacDjQyeq7lSinUrSHaXbldx53FTnGpSq/KEfUCQ2SPSHKD9wmene7uS2RuxDd1+TJCslLmS+pBZIIo757Ufn3AjGJ4RiWqrcg8lsk7w9fz5JQP8PTV+DldOlsmXRhAmK1eaqYXISAMU8u0O2mQ1R5nssepCTQiEP8lCPHqoTpeLGw4jU5bUrL21K9wC7ll3pGwLh35RX6NtDUaQjtzZmLAjFocmhMisMzUIrTfKNHVZ1T0JDlu/7C8uGlRs2MHV8k6ZNZ4YiH8XD1ZjLeVSCXKPLXjbudm7jpKvYREnTyzDJWoNH+xyXJmNZomwGVDqWpra99hgZsfXO/nQNc0dyVESRcsqJv08DDjpJveUOOz1uZSkvr69SHgk3nJ4O/LF/YRGyH798+ehPCi+0l9VZA6jGgFxG0wqCeaUD9ZKfc=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflared
    type: Opaque