---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCGF0WNgimvYybvVkSoRnVj/7KFCF6DkHaOdgaPYsi9jOzTgJ9HwKf5aPhgUxpojE4XFWOKVD86t6xcBCxDzIZDknoGudU9deb8wnAkburOI7xBSRmvZ7KKX8qiAzlW2scbjGlk7CJEizrIVEZhrQloDJy6dFYrwB9sq16b/HyMpc3O7nqkAKkJ2ZzB1DbpKOGkjI6DiP9IgwrnkEj4Mj1nm5pae9GBQ52rWm72Gaaew2ZsZSwwc6otNf8iazi3nu/FMqEor03KdM0xyZsabwCKriF2B57ndgArXbnZQtS6upemg3JaBLD9U6XSUoGkZrXHtgEboIwJfXhvOW/LJnCwupQXzWI+JiVvdMRcXoCHkLu1niIyVfy5I+aD2tj+7AzEAKBlKiCCnxsEkPdQhUkevG7aOmbofWOIk8m+yjF8UWAiZlfI7TYUBLX1CAtaJb0kFqRaN9tJnmXxK8fF2RDKj4zb61xM7bRlO0p5ZDi0AK2ZfgtFUoS/Ojy8scfu+cQbBQlejQw5jBmhzmzX8l4zB+U7OS+hfseixG9Oj0JJxpxhaDQrOWGssv9k+QG/1TdJz2sA7pv9FOJC1XH5wMTGzkroj6/xJamhEuqyTMm8c8PT1HMN9P10+g2K293cm7usc6GZTIWtor9TbgbloMskf0WA1ugCwKEFjuiQurD76BTm4QxJv/BiNSDyO1Q1KK9pKuowQ2I16wjTfVMTmxdJTOx3cfAQ1xJQf9kwPfUbDjDL3a6WlAUeyOmYWw8Ei55YDBfh0SY6kAHMVh9Jodt5tjSh9Ciyz5Vg4i59YrJpwKVp5g8PABy8WdcPqXrKglsTnPP8QbaT2I/74hiNCrevXFSAHYLRJX4JD+KHotfngtORQVyQxsPAfxdo4/OAp1DZgcQtD8b/E3VsDsGfudqVReMnzh0gElLHRwPj92dB1/fQScgbHEz5NO8ETbby7dt2+Cp9NRDfdINzFDBtVSZLqfqz2Ej7m5tuzSNxEdwy6L1jilRWTk8iu+ThNBWsI38=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflared
    type: Opaque