---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: downloaders-auth
  namespace: media
spec:
  encryptedData:
    QUI_PASSWORD: AgDEvTEl4EeAMb6JvFpSMMBRhTRkdNWf+WQW8+Kj/a5J2vgmuh4n153waw1nTmvre7PkAX2bxxCcie45ksSP0ZEp1Yl1mRFyeQE7gzczPxNcknuYQkSQiz4Ff0zQUHor0cOdKUHkgXLkvs41z0CSmkq7XZXfXYYWoOOpjZjT3pjtGwf+jNd3LM8ZmPLkHUk57Pf/4MgW9tVw7Nr2rkQSAN3UYZJ8C/OYEMYssvrFgGQ0H5OE8XoVM12B621na+PxslPsUtbPiRsMI7FS0ZPYfe69/SYus2twRXh5/sexviYbJShmACHDuMVeeDMLGf/+b7FZcf+rBtpL8wQbbybX8aqyecgY9OwauVrgCb6uEs/c8YAV6yERQdgaj4moJzuS014a+vAsHGJemmMRkRY7ZwfHEAj+IkQfgy+vARUsWhnjIDJB3GCbCLxZannLKBN7U/7oby8/syCSU55+9NPWYAS5NTc+Tgtf9e8OjbkifEF+LrZcU8Niyxp5Uuy6eTlVBikA76btA9rUbCeS+1pqXUttc1CU9zLNKqrTgLyR6hWcq9JXeZ0IGziEoGhalqpsLFnzDScvo0mT5Xz/cdQGaue0KBaLmcPeuPzbOeYAtAuvgrlAQQ+Jrbt+d1qy40UHFvjPZKG5NhCfPochHM1OFj+Y9X1X22frL/TH8al0CKSjaUZsIfdsgNtdGnZd+60CabHcH/Ebn2iiYvw80s0AmJlB9mKwVQ==
  template:
    metadata:
      name: downloaders-auth
      namespace: media
    type: Opaque