---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: downloaders-auth
  namespace: media
spec:
  encryptedData:
    QUI_PASSWORD: AgA+CS88R2uagVY1YhDgPqgyN2nRfuGs2GEhrIxO5kzJOx3QnxgDe1AFro1r8GGmb+XJxdUYjAScNKAx3Zr1bCXjbVKvqKTxKbeLynwm48ifDkwwOwlv0+QycrQ5LpvouE+99qvi1mlN1IrIVV4YDzroYa3hsyfaKvY+G3sAZPzo1XMVTXTwIQDZCXjgE26LaipkV88oNWenRHRwvF7j4pxMyKgbAPWAimYW9aU4MZ8dZH+O4zI0KdLIyIAZykLALihdDMg/AGDsLllMgHipdIjztIKwFdFf47vgIxKJZD6y1dL8ntw87unVee0onkSMWTzyiKpcFQWtplCuLR89rca9HSDeEhFWi2besAfXRAIUwhYWRSHaY26Ew33yDIueVEIC85+BE89f1449ebNbEIc3GCUMsWC+soAAVliP4RjNTEExBJKtKh1FzBlnyUarCsVNHhcEg5oz729dpL+3v36kCEeIxUVnAh5LtoMEx5mBfQYNAgXHsLKNN3izO3AccduCEjo3EhQZ4X4H8P1Nxyf/GB9gOaV6gQjRgauwwPMhZX/r+mEHN9DfLYyAVqevdr8E4uaM1gV4jEKjhK/E2tmXNgIWUREptRjx3gyiVbn217BdwBeBMWAuFb+IItYzqCo9mVTpJunWwevgrbnDSx6NFdyocMMWYkZp2qf8d/n/xuGNZAsqlzCZJpY3JjiYIrB4rbhzq0UFm6SXgGUWfV3OOa27cA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: downloaders-auth
      namespace: media