---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_OIDC_SECRET: AgAuBxqmfsd6BoJhVSqx/pqrGzegJiS9FjA8u+XeIr/zHnCusLb64uEGQMuH9/VIz4i0JP2bZsJbnCJ6+P3Llxxd6M12/n6tmkLUvW9ZQL9ZruHwHMHfwNrGyHUYFMIdWQo+qcu8xpP3PMfzOsTwrdYsMZan8pNLwcwajDRrSa5u1BhrsLPwWsvpzQ//gAKvf+nOh692P/BYv0a8Tfl+yZt2QKXlE7xSvLxjhfK2CvGF3jiOI/JkQFH88zA/Q5tQgMA8LbJvc9dRPsZc2Qcm6g/30oOOqBEp62cnRE5jZ7affkIvUkmRqQ0VnFpD53cts5PRhsWRSwPnS9wDbmbvOjyjGq+8fJwO8igkM2wikgvfYtO/LNhA85N+1wz3aRixMhiu9xo+CfAPPfgUmdGQ3w9iVx/olJHHuneutIoEvkOZFos6WPQf3GT6sK7PIPZ/Pw0wJtd4ZuJQN/i8OBsYJpuolEfKp7/OouthiELLNCdCYmJd6KIoA1KoZP02f4TypWigMgOxG+A7Nf37aZV6DVdAWuEWlKg4jDUWAYQxff5o82s9WagiU1UzrI1DiCqLm/K72R68ch6gwuZDgfa8cD8b1uwhLR8BeYbtNXdEYDWTZWg+90PxdZF42wV3Qq0HcpjhuGQbbpqFZY9/H/WZstWfuRghE0t2VKWAlPI+8EFC3hFbC2oCxqZNzvMVWdobAfhYvLzjOE2+tX8jeU6GOQPe95w=
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque