---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    clientSecret: AgCe4nZCnjIIYU0pM+7hQPV79sXuV5W7Xw5nHoNxSrK3Ea4avu2RwaOR4ZuTDMCR3RFTj73eGgCErd9h7OC2dVD1bWEUNWrvptyLN+b8xaHdRPpu+bPazNSmDILsS68rJGX7VoP5vuKaF+Y7ocTTtO/wU61ynBgnqipWl68iVj5rUMDMFDMqVIaRI6FfOUpTIrdTz0anZUb2Cc5BFjqL7xt55x4+hXw+mjTF8qWSa7k/dnB6wcu+KMeVMfgDcwmN7bsDL3b84kpZLpZf7SQV1lf3v3IOgsgmjgAgT8weEb1/djyUwuwhPp6j9ZU6hnLdX2+MBUGm4mfj5wLRE4b2ipQn41HfcvQ7bJV9q8WRNYcFnwzpsk6Bn5OfrcEAUzuNYaY5jbXFFYHMJucI9ZqwyhVJq5HTM0Z6UIMaTEvSCnEo5XAxrfTh5wB2oYcs87w8irvFLwZUkJUIfnf0xNIAkNOVBQbCyz5lds+tgWVVJkHT6TxcOmhtDSnowiWbp9RZcE+w6NuNJA06Z04BKPfXptDwhavXgV6U64W+xyZLHmiOCRNnutP/sfT6fESss4ZyziV2LtwKUgfXXjqa6P4Em7+G9n3AK1ZGOUAl3WHcCe6to5AJV37Txc3fKOR+JLhtkMjgCv+Z5dXpPO8QdchVrts2tHk6786cunz75ZWSg2bR+21xceGY7AWGlpeMovVL16ZRSXJFAz9WDSAM+ng0ZWfwW6I=
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque