---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    clientSecret: AgDC5kuZZ0li9OQe3qXybO4Szu6wz6192JPp4EVa8fm8pEa7Ae+Zgdo4dxfMHqntz5m/IjFN8+cUMQbw23zGkEfw3x2tJXsWQea+u1YMx9Zm6p4/r2SagkoDKThCI5YkvGZwa3Ql+HTnLCFvjBOYfQzXPnL+lpH/aFDzAqbcpYgNbcWpA4fCHShAkIyrBahHvedVtrGSpyiEkL0NYcKe+BZxaWl1HaAyKSiiZ3FnGz5XGosdAZFTEMtjOUku7d93Jt29c+4o/xIFqDsSneinZCA39rr0bjxL9qEnrZ5C7aT42LDD2VRd8RUS6PQXEwkQUgXPjcr92R5zJ4Yv1J0DWP7g2lG7nDofx4/efD0QbnGUaUg2bzzFUxQ3Crjl1ysfkHrhoupHppMjvrg/g5fjOS0m6o6EWT4Coll2BPu7mDAAbZmotE5epN4sGJVvghFT6+nBTYBloD8n4xLr5aG/ii2xEBMARd/qrdxn7DCsVxZaURISCASxjvNmhG6RZhBB1aRh+Skw4e08sY0PkvCDeev7bE69bcZtRr54LJtsK3JccLU2YqfxgFgIwhA7/ITFbF/5DHTXNm5kjc+V/FyzJ/4swq93Tr81CKzmDQqrvzEIlGOCSAZQsmStQcyMsmznrh5iEc2HP5Hk5UvVfEjtsvUbq3l3cAf29YF+jm189Us3B3Na31TsnJ8JqFuKG8ghWh5a5TN32jEoMTVHy6K0/Z02wvg=
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque