---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAx1xPDnFumylVjcJwBf1isiqTTbAGvxP8IYlq5+cphaa5hyplOtaYd2znDdAi2dWWm/Dufu8BNxn5RvYGy5GEcfH3Z6jrAYCc7SaQxr/JexI0x+nT10TcxOlGISckG1Hu42GQalnKNt0IEJjkH2+w6KDq404WS6nC7oKC5OgZVjWeZOC+O17rZot38gsYZkSdu645ipcH0Mipp7TGY/7mINAD1FiKbD7ENKsj3KFAwDCO4aFvCCDfL7cZbG4tz4obCJl4MG16j+e2nGnHxnIrrtXnHDA1iV1bh+GcqSUJfFwhafddG9JU/B58huvtGYGmPXizjJUDA/7H3/QWZJbqFtOOE/Pf3/Q4wvFb5Cgy1ScV1cPMmiGDaTMruLq5OEH9TfMbpNgboECFU4ZGShpRJt/np5v4g5lgA1zGIj0jpBjiYCdT9EnzbTEc/YjgVB6pMTY0B6NJadPwCMkZwYqLvNNlNyhMWfEM6DLM3pfy4WPsV+GSLjloub6V0FBNRH+mX6XrfMqpzFJg1bAb4Y70XJPRrzVfseUzyYobrKC3UwVK8Q9QxwpCFcXsxv1ckRoA/rPIVlPnPM82JWUCed8CVtmCZMD4IMSls8tBoo9WM6gEdGAEKThGGwQj1qF4Jk3okAAx4ig3DsADWDNZ6WU8s6y9ISmlmQmqjwRq2P3ixhWJCgw7RGt42vEzHz1+9H4j0U7Z0TsFAyDBgyfZTFRrcAKueMg==
    admin-user: AgBW322Jx/pGJHilPMSMMSEYZ2aNrShO8GJ39NdDNFS3HiDtTOryl02ha+r/Jhcs8hGXxJ9B5NOdWUgp26E+sTmYy6Us52Zct3OW0PsLdl8vj2JilAuYty4li9BX7LjdRVdyaC/auoUwt0Lcdue8cV/50OFUIP9rkrmqsqy15ncL0JxCtttqwUD8+ovK7YqZ5qgxRbtJiSXdV8xRSRZmMps4mCIjrglSaLxFHBTTaTK1RvhZ23g7uICrxF9CvtQHKwMhEoSTOXnWEccZOblBSTcqp9KYCy+9CZ8xCpqP9bl8Ssyp26h8GS0AIhlVQbVbHqFtt6XzDljh+nDLnixg0llY+sF5E1iq0CZxcCQIWNi8vtEuokWQgZgiQNxmZ1mVeldn+LJ1UUKy9aSoFUTmlWvZMAnV0mq0XfprX0g0TS4b2R3UNyj4QfM34/FkJCyUrsAy6ANOQPw03XTH6+qu1rVismwWZSlHpUtalPAvIG1atHiDZrkjf2J/ra1mrx7+BqvLaKdBcK5waf4M7oeLyyNLkOrScbHd1ZkjD1jwkLgN8Q+aCkJPfnl/LNWCxzc+WY+WzsyzvbAmncocBW+hUET6kXS/roelKPwTOwjoTg7GkaTgEo51eAE/F42WvUJ6B3eDV3QBL8TMRpvQPd2YGY3KlV8xfayr5zI3D56UZ+p0/NKTpWSXQSx1nO6a59Qgb3qcIWG6mQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque