---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAGMANWyfueclfaOcYT26unfqoSetHC6JrvmCH62CJp5NvvNnTAJB16XeVP1lF34gITpV66qbezrVIHdwWyv53kPnwo+duqaj0g8u9EfSLBf/cYLT8G6W/BNuE8Lh9WzjFI1GsgeRHZL6GMyyxJ+ivD2d7pro/owZP4kYf6/bYEvoEEMgL85x8ghz35X1lzRYWZJWquNvYqJR6U/W/tFg/bOn0+o8XWko7aihiDBtoMPPD8nkt7Kz4W7qcOQuLmEBr29a4a7YNVcx5Yv7hky/lR+3is2wSMVpDvLzTx6AzZq9ONyExHxVccDZtmEeZiFx2j8YyByPJ1WsBJXM9E5wZSnW6xzaKdvlKtEU1VgjBVF0xzJtra8cw1iJAqbVngsmxLiHqsY16LBceo25RhuvwCb6fV3twAIx87d1UTY+NYh0g6WYbSBx/klgZ2yJ/DystywA2uFZxv6fpdXpudNolK6hS+w3coNCj/FfFy+HrcEH2VTz/qLP9TqqsAgX0Avx9CfO4Xid6wjdp+N82xvyyNvKB/irxwa2Bh+SamaBFa68gD9HmyerORk8iB9hANk7lP0GGA8FFcszV9fuMN3vcPP2ShFmt9D8rUIVRreb6lFPZFEj7dhaLSftcOZ68bt0M0RuiIM4Vt78bXPkbKI+XczYUb3YbFhIh0A5gRip74TMsI8N46GPYNRWbC7BNGjFnoj6r9zbZ30+rbLBqzXjpSgZxe2A==
    admin-user: AgAbNoqOBoLMDdmoOMMd/GY3A8qg4Xt+2xU7YlzX3Q6aMGDu2/m9/DyYR4QCJV2lDaxybvr/0bYv5nv63MhKuNujUqm+OkZXcTM1KkfP+3xo7xWx+RwH84Wh8Lo3SINl/w6qMW5ITGio18ru+9fe6bENGaXls/xx6CKr7pZCuNOBoDSsCYK94jgyYEI7XMYps7Q9fkkMrB5W4MnJ+j4UXebpo6soXlX5S/YTlWbZmDCKjR9ui6ef92ka/sk+Xb3XND10zRasyDkRMSSSMbofbfNS4U4CDQkGJ8tVWnM1vosxCeUGSq793gH1Ni5/O5K0AaIBm94KKaetyfstNJ/1dzZSd8yik0mkgJ7UXNWEcnmxiqeaEms4+96n708aSkTx1fo2KjMTqINKZG6w82ItcBy4vAhX/pm6u2Meqi29qZTB3ol7yZrp/va/OGx43qETnLvEAJMHK2TuAIvcpSNTB41wgvK2csArFW7Zt6c/f5QrX2YW5qePB/jXXX96pnyFQKdeGikOnq41U6srh7GUYZoEt8GJbaNugF+k8ueI0Rs7reTAyZOZmRuog5R8ofFWffpMvJZN8CQVCxzqgv8ViNu7Vvto6oRZj+MS4nXe4xzJ5Q7wfMfIt0RfZHkm8wnGfgCgCKKulz3XvVemHvytsfd+UmxB89NebQ8rGGai3ZTPdavYRJMDd7z/RJoPUxhpEv0vuPZlcg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque