---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA+NIRSwshdB65ZyM9joC8aM4FawYMGs0bUDujsQEB+uucOTXUnFPf/PfjCru5MASXIGYkHr/Uk9cuyOMDJEUH3d0l28bc274Z5Wlpej/EhJbl8/X0tsmY+4s058EyFDC/NXOHJ9UvHCwSr0PWTiAOjS8lfjZAoqZKfMpV5ojThEwakT5pTeNFlpq0KfKBoKKaBnHTiFYnSHggYBHVaNI8XFmr2zN6JX+yjb0tvqmYr8+35vbLNJOERxSn3zfbWZExUTA7AbiqvpcUJJdpgRVnbdAvbAAtiiIgN/6fQ6j30KbHnbXE22ReQ6Wk/7Hu+iPW0q8vOAMD2GeCtRO7dv4mZEfZ2OVNjj2oL8K5lzO0k2AZxUu3aqj79bknESTwLkVRoF2p51opRVYbLWI8JykDcCQY8soCG6u6mjOPj1Ar5D0wLRzv/+ZZJD7FJ7glwBWVJcYtjKetfr++WH2VVdDc9WLjt1AxrhNh6AfNpsh6/kiCMFULT3x66mZ8IvLeXP6DYYXvbKaS1VonHKLNGQtgbJCNSZSij1rudthCt2jTrWFO+cGBDO2aJhRpsveMrEMYo14z+0i6YqujXQ9f3SCJXqabaSifRdPxcHqCpEHt2XKOgWqxGyIKd/Qn2dipmLdpYfBZECQa7bAZwGA9X4aPe/RPdnBVmdsGzkzweYebbPIXc/K2G2J/YGuzcEeQ2TtadiZC8OE/ac7oVKlH5hNOnVLu3Bw==
    admin-user: AgBAE+iSDje48c1lfIfe15HFnUiY1Jb1136ddO6KTqvLn7LcI39EIrd/Bs/CXBC2ZyTM6g6CkMEA5tgjvkxzSIk+QG8oDkAc3/3JGXlhA8Wd9OxhbeT2oUqnSABaY3Vc5+KLE2eQ8Mjcaj0YdrmNg5n62+Qa1lX27W9BXB49Y6QUYeqtw1R622o47lJvOd33mfLVsYeB5l0/R6GxOAz8/ZDtdwd393kbqx0aG4v1A27ikZyO7FI1R2doR8Jq6njFAFz0rSj7vnTlCzdLWO/W4i42fJI9JY0tVIB/NP8EnwwUkwpfFwJMwpGgM9UkR5wwwj58e8G4n1cboqX3mTfEfSFE/YQSrbgG/6SUJJxaK+EwMy1VFjQdtqMXAMJPAtlNU429JHGZgFT1a9URaKCZS9jHQQRN+U4rRcNhjzm90iNKPpWcQ/wCJ38LRPHBeVET85leXvM7EZNJdo2Y3txhwk4ulqrhEJhOMaSHliuFm+SgK8j/7aYmNIRn76ekhH+jYUVE2Jzap6zSvsotzzdzQKlvUIYKQjH3QLUn4FFPELVAfrhD+aFEsCEGdZKltcFS9AF6EKByPtzvSsqWrlpC106YaIyqomg4vsd+tA9I70FP3ltuzpJaUwH+K0iQNntj0UXJ0AzVNu0JHZuk17Kp+NyGHqQyJnCIDYOTgNVgv6zqw9Ed5pbpRa4FgvgYdXuT7gojBYQ+Zw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
