---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: haac-ssh-key
  namespace: mgmt
spec:
  encryptedData:
    id_ed25519: AgBb6bpAxWYCn5QC+vIrT5oKyzjdrgLtJ/Sh4NnHirKKZHOgWyMLL+rVSK+2VL+WhGxZ68ZwPPdRKEHDXi8eQXglhyRS2dgRe2VLg7wrGONHUNWBMi6RXfE5zSv+NvQGvR6hW45NtKjVgXLG7PVMqyKsMDo1BPO+JWGOtIhtMc025TnwvEyo3/gLWcooJH6CH1Dli7OQ4P4CGji88LemTSYjzzxHSEzL/eauAdE5s5DUvNTb9yFtz10X8u9sPiDi8ICZNa2hQb/2WwPZTaFQOaCiX+N9xDWeGyWkdyr4puYLvvmqrU7RVd7ckXrkiX+xj47cYiR/TPbHpNPSXIkCbFK/dJg4YpXe3ln7jo9C+fEBZgGw25AbMghpKqd1DwOwYVOPxRmiNMGmYVGjwIir7CPodNRRXvqXyOl9D8tgQTkNsGitg/i1ehREY2MDwQ1T3IkOcvBv6WbR90zZ9/drviwzKrgqaNNBHvqkcHCGSNjekQrGfoR8RxaQ4+jagNSH5VVLPqn9I4p9snko4jC69jdA9Jhr28RSv/49YaIB7/+yKuc81W5or1vCwRrh/vM2VSzmJ44mwlP+qlWX61Eht4skxENeNpfZC+tX8UcDRNTD7UM1hvwmFiFlvzaUnsQyP+LZi3WDuyIGKFf1ZC4LxYmoWNrPTRZfisyXqINI5Hw/8aSFRHb3fszVgHkrdkIW15gwA4C4f5pdXRpKBI9pDXF/nG6N4Iwhc7d2Pegk1HWCkD88I1de7lzKPfDoLyQ2fRlVDP+AGuAFcENyWLjVUID47q/sER5+sY44rtTiibL0bMSwe6Gda4X1Ct14DivvFVyFoKJtLLoo6zkIOUI2htorVgFZnPYNgttWYdyk4/1ItHzY09Lj53iRLQdSwtjpFb59NATkUGGQhEGKSwNFvMO+hQh10dQ8SeAq9uXefyYsozArQkoY6Qf1Lv2fXNX3ImsRqiLnqj6J4VE5AMCSIeaHnICLj9iX0syh/iWCHlXaO6MIFF5Y1+44jSc3ggQVEryIIawL1tPLyp4bXahtcobUw04WCPuoa5apEHnnoFXk+6EJUtFk9FPorOBRht0xg+ZdBYRAriZxBaoUyHEclLCSY0RYS8lZpZ1MMGR0+K+VxHrm2HYLqsCxvX2x1TIUW0D0rCcp+bFj86pMlxXURksIV075W6gHnwUt43zYCnmB9wh+wo/2nRjlriLOq5va0klPGaCNrdUC9PaLh7ARkJrX7Uu2XabYzGZB6CM=
  template:
    metadata:
      name: haac-ssh-key
      namespace: mgmt
