---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: haac-ssh-key
  namespace: mgmt
spec:
  encryptedData:
    id_ed25519: AgCDt7nFVVFGST3pEN91eqp8TOok0Sev/IbPUvnkLqZWOOVbNAyahtkNj0FI4X2DTViNaEg4/F2+Z0djdUhUd+dd9KZZfy4Hxse3rBXKuqh1A2dJ3cMYlzTKH/uDpti5BZr+GIVjbCuUFkVHxAKnGiLVwFV1o/hjJNLy+Pa9nGLQiiimJaY3KsCNXp+wJa6iirwsMLKnlCH02s/TOdVD75AcU3kZYHSSj4cP33pC4AaiGF03G/irtzL/SeNfP3WP5ScVM9N3ZBMaC3nnNNpDpEeVhwS9uUS5tcfuZBUN0rJltDu1U1oLQQ7IYUTpfNsQr037boP604h/5VfXICkeJv2HunR4/MmnSe26k3s7oRl/WtRICOidLYUPV/hkSrSNebGzu8tfyGxjUmJsVsrzisVTbdnplxaUm9+mshUmQDoo0BzOH1bJNi3pKEJhhAuuRAjqisM5d42iAn6efTKPQCrePrRPY+4JFlGZxlIB72we7jvcyeUAiHhaKwUjvmK+8fu8Wq7ny86L1t0YSDSZeNj45vusjFcoiTgW5VAHRmuyX8+GNuBJ5RW5SQ8Eq/94sQO+CNYrdzXRIVpkbdPmVZsJAHwteR8jXJPEZbNhf9xuvdpEWk38dKMIvfK7yAfljN5UlRO38XcxVIkEd4esxmFovxSFpzUwTUPDe3R2jD94Th/WEoOLhBqWE66S7EUUop/CMTjLH6W/psjrl0CC/sp4Q1igG2W0frjYlREiEl/UqWkzSo048NdcDRprwpJdzKCYa1z4bptD+l2P+nvQDtO5NFhi00hNScPBOKtfIZaoQ3yuiGfd97UmO1Shx/uxvvbtyilfTWK4lHs2nvEktivSwlecwHPomRz3gdOi4FuIjrCcn/3pMBP4o+iLNUsihJH/WcF3475kXzuABhDlzA0YvUfDW6hm+nwa8XIbgG3xs+PxBZwlWE0WTcOWrppC7F9hp7HqnAp7CcGreFa3w19WC8eFzfGxOdGHYwrsU3NeJ80wvX2INRpffOm3f0tdtp3eRpG39PamDC0Y2pFhf5I18uEYKJipKZnxal3f4x0kcxshzmkVHBF74JbfFDbaulUl3QJb0l1KdVVdoRGTILNhk3cO/rA+QSnawxJsjkPSWPaYAI2WQkB4+nB+XURc8SDUxjkZihcdqsR9cbr/bphwmsynJEkYBTjJxkHjRdtSfTuzVo/6AwNbJOleMdKVeP2hQBG+mxM1pfYtMyyG5GZ1obVo0JgyF/feGgE=
  template:
    metadata:
      name: haac-ssh-key
      namespace: mgmt
