---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: haac-ssh-key
  namespace: mgmt
spec:
  encryptedData:
    id_ed25519: AgCOim+TAjoS1ZWA8L87bNX/WCJRYe4P02mqHNxfZ0j9Ebi0SeGD5zSGZL1egCdOIUn7iSdqim6szsOdvlkdW9+CMo268c67RlcuJiFEkrU+pc9zHBQ71ykPb2qxghb9qG4mjzXrP03r01xzgJAlO1a+6rVmFw1SonMuWaxCdA0GJ6GmD6kTgF/ukzgSJjgmglyd/sJAXr3I/KjghMpmvGrimV3gkd1TN2YhSQOF7dyJJmy4of5x0oS0F0XvKApR6nJSoJidFxnZ1Shw4bDWIbVI6smz0WxN0mBCcx67u29QEYzL0b9zXKgrJk1196jGeX7FpGzYkY7yL18sWmakIf9nXOAwqss7qtVS9vqOD4p92CgfKcjXrUOvmM8lv6eb6btBU2juUNqNSmk2RuS0qlf6EeWcvuYP/MAo5r9EMIDaNawoCrYfi7A62ejcB/U+Kyc3FtT4VJYPaU0xpHVuf72rgUqy/iAJAIkGUxpiSPfMY5i+zzKMsCoURjDniY6e44aB4puyMMG1A9F/cg2HFc/wKRzCYfoJlizmUMzwEIIu8bu/S1AK0/kAdsmFvGM3lFMLzdso6UEE3hr1eqBW8TyOuwCmhdSXVOpmPf3rVoR9yaNAObJERteQmfVTxMw/hrFgPK55D5RlTF8mJKXwFzlo+2b4vtMR4Dj+kduhqfEmWS/aKGA35dxDh0U4GeykuBVXVfexupkOQOJiggaVpXslc9jdAZf3nD9bXMmLCMvLiDkCHm57CR/Wdw+b9/Lx0b06j+4s95ufW2XWlJ2LbFO6KzKwFXlOlUWpK0i1Tbq0YTRoddouO7YSZ+msEh8bmsdR2O1lHrBVHjXzxg0dPoFmlLtqMo8sd435G0WOtvsHuTEY90B1s69v+K/uZJAHUO70a3mOghQwfg4AMOXEwJC3dBZaPGSUZmRP5OLHoCIJrUFLu35ap1zPEkE8T8B+gcjfnvpzfZiGAWNXNpu4UZm5iaLjdHu2FhjxaICVswK8Ey0GhlFmO9MuLV40Y6VFeUfWyozhKYN9wlfZ/4QwUi8YFmvccfhAJIgcZb/XFBU6NjFmMdBbbP095iPb0kbq/tw5fhoRYNV+nOwMe7zKOeFkBDZ7uiLv3mcfhrV8DK5TzqwZv21eBSj9uuWZP5iQzHZLi8ArvUOu5we1mRjihMKeCXVjetGhJN97by3IQ3ykZ9vac08NFQhm89Y2YsqxClD2iM01NN+gY72ggYnjpr+C7O+vpwqCs62Swgw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: haac-ssh-key
      namespace: mgmt
