---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: headlamp-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    HEADLAMP_OIDC_SECRET: AgBMs85EgkyXYRlmwBacn/XAADgHD0HP4l5Ui/EaBfLS0ZzXlnlQ5yjogFYK7DAAGVb1l1zSdSBGOxLWstfNax7SgARxphcFf+sN+KCeySajjoogAtrAPmGdqlUdJeNTrMIbWBJxvhlrpH9yo8ZVT9CdKoLoFv4jStlZsHjZ2wJr+6z4YiTrFHMdkSzFpAh3jhEUbEPIoKvP9GGdIeD2IMN4+hKZsCcY/vYvVAibOWtoDGm4lHBIXkr1afdC5h8xD7BCow7UqC4MZh9QtNidxTeyE4qIs8y1FRjwkNz4yU2pk4LIDQmeCTDiiByT0HoEKQ/TdqFGFqmgD9Sc5P9avPEJeo5QyGh1crN4TexIq8rxeMaqBeygdasan4ABNBZVJUiWMCdZOzI/1fuL+TJrCS0krpPuLst6Os1qj8ljiKb2YjZPEAEE4XHOCjw6JbWdLbKrgQ/RAbbX6OZXRFzjfMDsGCbq3Jx6s6NpS6l4RZFnZGvSBPxiW8Vk/d8U0itdX3nro5h+csW5LInwpF/jW+0xGc9CdXtk7FzY/PXSggUOnNW+IQ85wsflgZOm1stCBWGh1lo10C5h85+WNcO74qNEVVc1gK6fIccyuIrF6Vi3SKondhkA6/fSyyd+eDdeTYaYm5RE4pJATzf+4qfKatC5gH2mD3eNtxKGVYtjVoODJaDPtmoNkUbe2eYQ+ciG9NezIXPZuwhJe0zPqbsqkEHPqjAlomsIbbz4/jGV48y7iuKu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: headlamp-oidc-secret
      namespace: mgmt