---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: headlamp-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    HEADLAMP_OIDC_SECRET: AgB48bg6OraQqEYKsO7dRz1ui3jzfNdL4BLfKLZgnVPja5bZ6bH9sepjhhqQNjB+znc5Uz6p3BU78A2+NfwQa3cKkn2Jg17B5A9k2pm9St78JLQV14UQzhjmPoBzPECABCHg1gdXTGw3uigFwaSg47JeR1Yo+kO8kn1jKsjmQuKNdW9BuM3tivPpWeHCfCDy6L3J1MPbZwE5Nj7wBhDN2nOSMwilUXISuJahVFi8qVRkPCSs+sJlZYybIQLyCMK1c+PCyNvHnO4BKuljkthK05YQV61RaKS6GpmqRHc4CDkTr2+nJj8f6yjLbmr4p59vEm53AF45p7Iu/Mkj+AI/7KJtSSRJIXf4s7Q6wuMJTcSod0KJ2fQlrSBPRUpevVLW100wuMkxwK0OVxcDUOSrjMTbKx2d5k6fEnU1sqT1himW5n2cZIhS5DXbR3Nra6P4llvknVfTHk0Gla0bGxRJ8VZ8F2y9gPuNERJVv80ud/dOchx7/BHzlcMcSMCIVv+saaY4xu4UT+awi6qmWXvF5r+0D85jSsd0R7JiwwGqVcNFe9SOGR0j6RJ5vCN3HU2QMHqoxSFf66lppCsfEFf0NL4a8gk+YbreMfULUoGd3/78UhlDrKAbGk1Qu3XnB61J15Vdoi573QorNhD04IJxEkt9M0ypbTVSOcHTPLuuCZeTfH2ckgtWWB+zHodb8bB/twTvAO3QFxuOBeihxiY3ZqwOeQV6pR0bo1pSmAf59Q+C4+wn
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: headlamp-oidc-secret
      namespace: mgmt