---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    clientSecret: AgBxFYavRv4kEueo60Z8CBohqiFwiopiTPUruJmM9RWL7u6+qImRoIaGnXqO+KELHOlzfG7u5zzkhPfzonoyo0X8CVm9uKyicF9itszoOtc2AbrynfvKoPoNUcV8daoCeW+aHwOPFZQZoGSXWD8BbSsIsqrrmFWCvD8PEE/DjAw5hIpSJfZaWalBF4XB8kyP+CZ3mu1kfDtOlVf9a/9L1vZHU0aMVuuficS6e3wARAzsA07ffjGbL7v04PuVfsqck2CZ2X7Tdo0vWLOiPsKIbT7aDd+i4yETIpYaBnG4Cwi/7LDZvJ/BBgHNgdK36KNyrRUp3y/XteXavfTzk+djZVwji/bA4vF9XrE1JLQ5P7KGbpamLN/gAhvodla/H1MRdM1SPFCHJuBkN54ZgErDJweNedpmtmvgSXj3yQEghZeteLpiJuTiD+BWwYrgmiykWw+yBxx/8aAAKITok9Jle/aJ87Sr+QK4dP6tqA5pPqAJiujxalFvpP7IjKCYHIU6VqQUBeuhIlsg3tM2kUfWT0SP/N2AF94MGnYtRqzqiLZLaBdaQb0ggiCD1vY7lG67+TMcgnIv+1HqrT3l+1LdvhGGkERkKzSvUfFhZQC4KfbZY0qZu2DXvo5msQ92FctiyLBkttwAP6OT6vOGtwGoovTpUlFaOyZ90JWcOMF5o/U57FKf0XDDeexdkc0evpFrP7V2D3hJK6d/WS6J5VDkYsu/AC6MZ5ExktJsvEe1NtVlK94n
  template:
    metadata:
      name: headlamp-oidc-secret
      namespace: mgmt
    type: Opaque