---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-auth
  namespace: media
spec:
  encryptedData:
    BAZARR_AUTH_PASSWORD: AgCpijFeCax50DXjGaXFicsHDNe7nujECtcbQhCO0E5TEdNfkBCDtdShBV9NJc1KBuks6uwQxowSylr4uCCeADQXuT482ay5SON5VwQ4cnrMIckGmMxHRQvtd/Wf2od1hzvEcUqo3DknD3Rdq6Lniuq6VaZgtC936SBfbXFXo4Okm+0QVfSZe9Z9L29NThNW0hiwwSVoDX2gbqE9Z7x/T253ryGTP8SzR/gL+naIBjvP5DB2QckfsX4Q1wHGuk4XPn2b5Zqbs9f9QVb3SOgc5LNZ/hxcALSjbkXg5/4hKWLCe8RIAP1HVsEICj4wA8/6ntic6Uv+tZJCTmI7TT2EXWwmZp3r6Cg+sZaHRG7SxfkvbyPWnGLRIHv7Z4O1pX/FO+vYJ0lV7DQFoaUj2g/ZHIRFA4k+ohk2wLQLeyqbKyE0OGJfSjFAJgp8DZXIFg0Wi1pJGswkAQzq9cNk6pwjeND6JHkq/uu8gOBejHLY+r/hR3sInt5h5NCrY/XKGzXDlA7swBwons+18Szy3LVMTvnPm23+q5bP7tNNpB6PlbSY8L7m9PaUVaJ0sQSNu9KUVsjUK4Jw/b9A9PAmeBM4TiHUWmyKQRWE0s2QiwiS1QZOboSTkgWVsN9acbDlGIR2OKO/Bl0ljL5C/paVUQDzXURDwAhBuxjYEfH1YXPcdQuSh0jMC2gXkh0t3Tf3KjJ+u6zRuVGqJaGE1HQqZjajCWQzb/5OSA==
    BAZARR_AUTH_USERNAME: AgB5H3R8gO64tSNdhC3/GZKa866uo5NwKg9MDd4IacNjllEeZ0BJnvxpowmaQarEoAzV0trr314rqErwK140QHnOO2sZuWbGpNomnjae0IuV/OIesekdX0i+gWqQgTO2A8IAA3M4779oW/YRcXZh2NV2LGU4Cxb/HhnzWJj7gMFDEWVMQU/8SOvITrTfVOxD9UDGtbye47fzDAwnCfVEUui73RGDK7YqqzCtDtjyCyGB2m1BOi8p6Y6gpEru3yyp5+rQaA8SubcVD9BsfdPFKlIeNXH7aiP1sI6p3HI36ApQLEf5iAkzVqa2+cpxGKEMT6/ZETH0Mh4uR361PR3obiTR+g2Bj6rGGXxLaRjFOg/KznrzObYQ9UMgCL6LbGVsq9Y/55dYC2TgOmo82/ny17J24jgCXAhfVMgNn5ocr+EpETtOj/J/OOg0Q/BEVGkUz7XiTS9Ui341oLpnzRrPv94K0S2Bl/z8vEGkMHNxhHmgeLgXJ4WD2+IgqDmGasGqrjJnaS0N9txNUIoJ81gF+JmBy4/zO4hemiHIGVk5yBND/veRuI+0cwJXgREF63M6rf6dqjYTeW5HrYnniu08dM/wkTKTeugz92CKxuLcTH8yE08VBKmXKjT6VkwuSwVn2TfqYk0v2/uhOSE/F+lJ9R7VR9/QJfIZxF6N6IB9Ch194iuZyivWMDfHUfBI0zv3o8VnoU7S9Q==
  template:
    metadata:
      name: media-auth
      namespace: media
    type: Opaque