---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-auth
  namespace: media
spec:
  encryptedData:
    BAZARR_AUTH_PASSWORD: AgBKqkud0Nba1cNh48v9+QESrwCTLVJadJYuolOiWYlpLFGgPcYeUKDwV3Ja7CzN3TS/n5oCqmnDPGkMIae9otnfVCZJjw58FD0XvUayuJdpgagxaYivjyceqojm8W4SfbWkM3vsKH/Oq78lEnXzpdE1Sukph2xWIcrhspsrG9TLP7WoY1jzri7zAPhImsjn2csNLQbfrM6e1IJqawDuXC3yKkw3UjghGNsqpEt6tedAH23Rw73+Z57a6JkYLydagVLnPAxmoCpcFPyT9PLPjf9ROu4QN56pXKdxusPR4A6VKHo2qfKwRQaRCGfWb2CEvQeNDrZ9kcVMJmApDC02pAGNE5tpivashwGjaMyD/W0DzmohEeKZM43PmTqVzWw2ygc+fcRJ2rwGwlaPHeDDMBVAQwx0jJgXcaC8Jjknx+tVblV7A5F6UIZ7CJ4ubTh54WE7zBgh5f/NY64deT5tmhv50xJJJmfFlGwj6MnVXfdhVNGwL/3e1ixP2rvvALGQRjypbsccxJeB/j6pwHYvNATIDdzqzLKMtGAWzm9BpxaYcjDrADAEJjmr34tHJvAGmwBYEQmUodECytkKHXjbtWFjyW0ZMPVWMn33fjvSA9Zc+S1TNEsjBOVSDt93QLC7T7hVOJqrFyRMzHWgxrtsdwMe3sZwTqmhVAVyrrVlEjnUR5O6pukI6IV7/GuheJ713lHOsqYfuUb/FHyPBVwkByZFRq8e6g==
    BAZARR_AUTH_USERNAME: AgCnpZ87m2igefD9fEpYQgF79zw7joyF2fNlQXm6mgOePkRvUrBFFEzhkKMGnQ4r5yTylgesf17fAo9GMRUS3eZOED0V2qHTZfsPQDqDvXzU1surd044GfLCZttfgnN+lnap9qNz1gfGkYDQr3P1TLQ1zVFA39M3UEE9lla9WvypoUVP8VF+yJwCrsIdENYzEhtqNBkw6LXlKwB1eFQk/TOvimrlL+/2xcwXHBK+gjH1XR/25HZMb9u5QgYejsA6vkoGPfgAhtvODKyzivJFLB0R+XlZbPH1vSXR6w5dS2evD/bTN1yCPacLD8wBXt1m3z5Uyfr/9vOlmImesBjF6rV7jlMgWHj+C0idYHZOdJvY/VnFpj5iS+XNMLleN62FAs56vDjQcl2Y8NrKBhhol8+ra2qdZq3Y19wWXPO9yl/cwzlQ4RiBIlLSGLzb/FBGFvqun/PpLcMSLsrW1EyJ6i2vW8XRO0G3IITR8PTJ422KJb/P9fH5h8GYPIZ/D3yd5YhdYeum9UXR/vl4M9K8/wbg4wXQiK4Bo19A4r9PWBKWOcnb6aMKQteaVKdof+qY/AfdO6O9QRQO9C/i80tHL1hIVRLqORjnFrL49yYu63+g2Y9QcVwDavySP7wr9mTTW2VmJyClvoiIGXjttBSp18HOmtdQMGNRO7eqZTlzgpkr4m+HinoSLcnLp8ZE/b3XoKolz52paA==
  template:
    metadata:
      name: media-auth
      namespace: media
    type: Opaque