---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-auth
  namespace: media
spec:
  encryptedData:
    BAZARR_AUTH_PASSWORD: AgCB/i0FJuXzQsTFPIxwul+X4maXDMgbuUQ8Na8k3tT4woSFH3nOVcVxedsl0TzKJG10VZnVG8g1tw+fPTmFo/j7thIE7RLxoz5cSUbKsmBCEqunQsGp3WQ/eBS7j96sC6yJzdcxC3cpTDTZpAU/FrORzY+BwzWpqFtVWYfCqWm/ZQqaTNn9OnLsmcWCus5BKtRGlAP/fp90tew0K0Bpa63l7x2sLqcz1gTv108g/0UMlc9XWaclqR578zC6TT5uWBYhrMxcQpsWBqALhOjsSYcS4zCI7EAQI0wuGHyPN6M6MoiiNU9NR3n3X4BW0YoyimusGEDwBxR7RZvMIc8cpaia8vJM+xao5+2BdcRj8Zh6CTAmObaW3ZibLbTi8z3AztC2pY3Dd1FW+vJ8JMNg7l/2tubEOs9X7b1eb3OlZR7GKqZsDiKGNf8ec9XAyJUCzU+zsCOQF787kc21P9RY5cQT8RHtN7F1KQ+x8z7RxW3LLwes9f5Pl26xzeQA0BXoulVjCxxr9sjnL17ERSYREXD2E4kzKwRbNGY8MSE7dMXgqrayrXIQ0pyfNm7rk29hE1uPP5+xWQ9p48rv1fB+Mf1EBlu5WvsedpWPxXGRaPuMa2xGDhvhmuIpczhMURXNvvPZuS6s89/c/b/m4vKdH6eUbRhSts4BX4hQrhtPuFmw0ruyn9xuYkAI7HnrJqLous5+HgK9z1G0InUCHmQpo7+/MIhwqg==
    BAZARR_AUTH_USERNAME: AgAxpWncyLzzO0t54OI3q7niS3WsR1wnvABuMXh6YIAYs2yV++KuzFclb1Zrt+N3OwczKbMeqj8RU8sezHYK5t74JVWxf9VSLlC93lUdXlXU8aLx+HTUA8brPV23FWa8utzhVvLeU/H6clwl7ikZMcewugXtxPzJpmmJMpNYYrQy9OFCE80B7rQGhPC9AQr5o0NjGmlIY4z0rYH31dDfUXw88Xt9JLQRQOfJeW7+QUS7uVkNp0GhavMXHhs7AZuqmpm5siwoY5FK+MeUiedMs6Ah3n385D0SUN949zE8e4likBboE56GXVBbInzaiL+4fahRhNhulS+GTE3MVJdnjDRdJG0Vi0+yuRqNh7zHx3PyBs1UdZfQsw7KIEp5dyDdiyEp5PCsjGOvAQKB4PG+VN1Zan/nWE77YpAWM5boh+CnbKyQuGItWTc9/U23oc3V5k5qgk/oE+5eJUffp2o+9MGqC62RhEJDlRrBpc8TGW1o7LuiEdzI08VBj/lxCcgr5EY4CV9BKdADlkfksQkE71uxfHd5LzSylQEyXLAENfyihtZzywZhw/BbsoSmanhX8n/Apc2Qd6l10bj5QlDpN6b0fd33JhouZdOCqFBQuZvgSZHftasXbqyF1NfePVfbKN+a+JRLa+zRy80eRKOquF949AG/kIbue9oFrZPZ+Sl0fiT9rpyzssujISjLhEMXmoAIJkgAcg==
  template:
    metadata:
      name: media-auth
      namespace: media
    type: Opaque
