---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pegaprox-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    clientSecret: AgDnX4wtVVuuE5G99wxgPShATdJwLmgV7DzP+nJ4BpV3/aaLzaDu2WTMoW3jk2eGwCgITgiyyTj9Vn8MRBqEMfDvP+RVixGZVv2n9LbmenglEWsRFUTqGJRZ3v6A/2rtn7sopwj2oprzwmAvqkUhylRKSZ04J9J8y8OuGplykkOC/hepb/9qcczYQeRmVdP9ZmK5HEI5T+ADOS9cXG0h5HWjJ9kr7Yd7sdtixbzIgsb99XGShzvy7xKAu5EgbnvLErzP8sqCWrmw0d07dogvdqL2n5nMZAKLJzic97cTp5ydqgEXaz03B0tqe2MEOjjb9GVRQiAee6iGeFhch7d+46LT+vWB1H4wuqbMdaESw9F8Q1zKpxgYjndI3gpzzYmORTxalHOSkshTNqgOHIZS7e4iLl/ZWV6Oal+gFuvFp++FMThlVcdiY6by7DGEaJBd75H1tRoJPIMav8SH2tcnXNnriko+J3EHU6Onebufz2DcXiv0ioC0DJgo3ClBaatVrkbNpSH/1chtj1fkDa7ysOGLVRlktitgx+VCABMsv/c5kgg+aklvvqZ401sNVf2CgXKd5swsoQm+LtRWPx1+smclMWdyzEHX9OyBFgvd/A3lIoe776bgS0rz8FVvR6PGNDZKDgA6pf2fQWXCq6P36Y5wivNJbIkL/SvdIlneJ8Dz8tWQnRP9p+pjEgvt3MNcEHhsaIvI0FoUck426aFSyU3D7dzkDrOTANcMEmQoOm6hb/HeWgfYp/cDESsBO24ad6zzIaLzqWh87F7LtQvcWm2m
  template:
    metadata:
      name: pegaprox-oidc-secret
      namespace: mgmt
    type: Opaque
