---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pegaprox-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    clientSecret: AgA44WpJ3MGwLEqW+zIArPK4fAzb98gJZ6ZxF+vI3J8SL2AF3XdZf+V1umP81zRBZzdaN4yV5P3I7q8lHZuRctV+XpshDoigu85gGB7JVdVxjH2+I7sNKwqrknijRtn1e5/zeOksINWXaxvJXfumvsNMZxcAZCPov8g8cmijgmzJ2WyNZ+wBCcHivgSoIy6kj3LPGwuXIrE+3Yh8AA1fdxXX4/5Yk5kWOXJ0O7NSBd26AXUzIGSbgTp4Yi4uHkR1ZE8NISP/eSlPFH6ihzNUdrnFTp0HFYeaUsZze0wz+Qu/YXHq7fn1SVeYximbAzQCzmRWU/AQrVczQMnOLB6IrooUK7jAe+5+TSc5Qdp+fY4vUYWhTkaUQfVkpCOo2Jps2pP+oBS8lHSGjXomEBJ9AQN/hVQY+ruUBhTf/PSivJQxPaGM/NUBKh8LZy8joDTzO8WXzROiWRj9Rf3/N2yg8V/KVSDwIgXwNvZ1IXQLIrVvsuc9ljVlNea4QiDwINwt8R5bfZS+PP8jDjfBuZao7Npkqs7pKTRQMJKPzcS5cHuz8HKnoaom7aEiiabOdX7Jxso9MXM9ouNnEpysHhFckmw6jtBBi0dusx/s7jOdvMYkP2EFuYg7+DM5HLVCp0l/tTp4FkWVzFtwtcJl9FuUPwRYwy2o6e0isNW/Hy75dUcrufrcmsdkOb/14lYUH5iKgfVLC51OLOjdyBWeL/tuma2htx6ypTaxpuTsajUKwxTR3/79rQVbjvUeXcMrYy3Bfwz8I0ZK6fxogv9HgOXDzudy
  template:
    metadata:
      name: pegaprox-oidc-secret
      namespace: mgmt
    type: Opaque
