---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pegaprox-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    clientSecret: AgAF43topHWQAugtRRk20f65GrlnlJiCGqGKca8tbIJM98Rkuyh00/dMVJyCvx/DJgh9eRBUPbqpJ9tTEJ4TM1klR9P0P6vHK2ILoyd9P7taY6HFEdIPK9cPhXnDTBcBM972ULscRJh+xUbBKjxCL9bqnRk0dZK6UCPk2+NoUQQQbTf4EktuyXOkAJ7dtraJFobs41GXg4HOe0AuYby/v17FplHfhH/fn+y6EOtz5T0qsW5S0KmXLcOdeCdh1EwtU+UH4ZFT2jRO6EKEC/ngUU+sCcHbWhX5nApBGjf7UFXpaRGquOID1oIKPnokJly48Otz1fjGAIxYNCp94b4l5dScxuMaWNXrWvl6+Y4BLqxFxvtzJsIobbZiGJjrk2w2I/p5Fka2kuuij2uW1NzXWEQ0gC5P3OJsj3vo1LHKPeaxxS+Og3Gy1fFZOXBsxU9cV2iTypXBk1TfLNWQRv/hJMC9W8mJg9BHkWC4jZL1zUbo/MvAQY0jxtnh6hvyxVbyPmaKNemBuGCcRrJ1D675M5ppNkyWRq7Gyn5sKfSZLClAGTdboHW/Q/UpvnB/ky5Hfnx6RJfUDwZZyozAEDazn+eShZ73UMhbs/emyE9xA4pdpFOhk7S3asVwGIjw+FoymRWWKtJOC2u6aKHwEiVYjLrvpprx6AF8bCADfWfaIFvqxf9cHyNe2NEjsYNL6I7mV7tgRi9xlXFca07CUYgfduHDMS9Pa9G/3W8vzAaE+TxBiyYoevHLAt6MMTg9paJ4bywUdn3BvIJp9nzIJSYE0igJ
  template:
    metadata:
      name: pegaprox-oidc-secret
      namespace: mgmt
    type: Opaque
