---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: haac-maintenance-ssh-key
  namespace: mgmt
spec:
  encryptedData:
    maintenance_ed25519: AgCD5eomuPewYgfAxxXbBxbNuiybhVnRmu62rypV0q1yTpV7jYKhS1i+yUsHFEAXEZhDUJrUlyGq/+rMp8x6JLbW3Mw0xMtHGnG70sVvH77k7kY5NfgbahXE24zekxBjwqP4HgeZEUdTe4/CDtCLSL9U2Dgw7Dxjo8A2tEB17gmsGb5TMNfoBh2k+9r2uixYBELb9wFrp2O+9ztCoMVnh2RtUQLjwiCiN8cOi899SDNrRoAZlOyqOSCUIAl1OdVVYekYllG6uX/0J2JJLuL4IO1FsNOJsi2eOx8qRUu7W/3W3tdKg6NPqhjY41k/iW1zBRrP6ah6B61fQTxWASVC3eepMF0kBXi5v5N+K/lvmhbg1DuSVQXit3FIc3MQ0nIhKh3qd/B6o286aD0MaVc8K/PzqQt81LFemPfsxCFLWuTEft4X1OpXdmE5PivZNSBsPhF1TZs6XmmZWU5awlO43gwrCUvt77OHBhLRivwBJYvBKb/veJShYCUF1+YLfIyUz5s71OcM+55xk73/8UDVs2/kZnh84stK/HCEWX4jWy+qmESwPzVdTWzQTnOAA9iqc8jcqJ6yfP0K7nZaEZYb+oC8nnrl0iOLfSDMZRlnWXixC771ZJUDNfv1eL9Smcejt0oTrjRC6V15beW52BuIqDqxCTJexybYLo9oovlxYibECLLj1S60L5+MzM8lx1LHVx9CB9YlqoorLTQzEWFCsJisHGieUBeqm7df6/3tezaeLiuJVok/XDRj8RXZPUrrNsBaGN3UZfHpKIy98XIGvULfnS3UrSt8rQ6+eQDssHW5/vsRD45vBYOe0rhG+J6LhcPDqwZPmL7LnzM8zATQjZZe9j0SjYIIQ3m9oTjCxCOM9KP2zxJZh7CkeF9z0OBNycE5seMnklcr4D4pWEkjf07PfkHwGr5HfL+FpMON2ngKCig3KY/m7d3X9xSAksKmmfxVWWLNv0O+isqL9JyR0wwbckJPkPNmuwsWhBph38Z1Ap6+RheZ6N/zSwrJeLD4AQY3oHOwx5i2LfMmjUS+OTUr5aDD/+bOVzxEh2tPdV7rrKqxh+EjdWPyqOPZofzC+roIoVQrZDNLAtJ/oAfIHJDTbunzTp7NqlCv/oeShrXFJBgBc38QI/h4fh17OB3ke1Qu8sxpt1JDTxm2ZqP5WYBoEUjuyFgcxEP/sqOYlEMIdMfpKHF59QYUUx0cug5CE2Q4ias2y+hFc9VVxx824pFnPzh9DuRH2GSMveQ=
  template:
    metadata:
      name: haac-maintenance-ssh-key
      namespace: mgmt
    type: Opaque