---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    SEMAPHORE_OIDC_PROVIDERS: AgCCeha2BrSh0cyFy0KN14AJYSpvmB5IQpK2+iqXF8x2I+9yrSLbWlUenxfl/a4bXDPKsmD+8nmBsbhBKZURoEh8a4PnyNfkl7p2WOr80pRIYuh478PlTzXS9DWnGrMcvsiC/jbXezUMXD4gxPxr64R1wz7I4isGDGS+feD/89gGTCs5h+kDU+7NQsNff2m+4fVjMmlA+OVbN3Caog31s4f4zn5eU8XSfpPD56FzFuDJ2PsSMydELBRtO3f5nd2AXYPVDlGOXFpPL6i2x7eigu/R+uDTo1nbirvO5v+peWELaatUONX+fwf5NDZON2/1ztV8X8lDC+fJz23z2Nzd3PGYCljNgHfeSUtj7hrn7MA2gJ21enIyUMGjNe4R4JF1/CHLMMJfOYc8k/pnIbatNgPPY2JRA9fW1e8U2FrsW+pd5IMqkCLcCogiqNFNWYQSM9RBrcNZ+neHm0B08llJ5BlA3dl75pawELw2+gK+Si/+0dU3py+FgwRYxVFV1fq+U09L9/CQv8bsjLYV3yvf3B4PV++2amLdsE38QcjifOxlcJOebG9NRp9TjLFEJH3i7PSnMqQpDvBp8LRZVx85MoMktUPJM9F9uAG+Brk9AhsvBuX6c8EzoW4HwcqZef4FcVVEQ3FY4cQY7lNIgvN/N6ZGx+5PHtS68FYN2onONR5MzCHHcUsOnC35vMFOTNyOkB4aKD42wjExQyC9iKS5RaBBIqbfbGV7EniHaYVims25trt/ZAxzMcFUfmLtA7HEqk2FfkkcgtWZQqb7BOIHAxixXRyn7IsFsbrf2nmmLI9sFkd5Bd9GfB5Kr815gEGW5KEnQzEodYGg7NwS4UROX/a2C+XQN6tw7MygzZUhh854Pt0eL7oODN+NBOm9S+MAk3SAhnzGLU7fwkbx2YmCmeZTFXhPU7/jd/ZyWQ2Bqa+gYZ7nXr+InHbt4oJO2OkXD3wk7lgaa6U9nICtjlv2wSDRxxSYjsDcK7cYEqVOz9lhj5xC1xBHDtvFLZWnPpLCG5ziH6T7QnU9SkNDsrrnuvQ233nrLkA7cJE5c7F9KITLbTcgfcpzav0hbizJt6j8T7f7XJdJaaPgx5BJCSPdp0si47vqNnZVm+/MXAnlRgCsZZ/BryS5743XmtiTL6f8vAvO+6g5XNPxfAFlZzUFkthappFsACzo9BlJ1qf/CCdQMnTn/mfvccdEQ5mJbAIGC11687oowZOGZWofjG0davLIkgFT1ffvDOYlh9w7M1l0XVYGdPxb2nnToUBMOLRicFHleJbg+AMcyjOlKCYIqVZlq0g2HQQF6v3cxg==
  template:
    metadata:
      name: semaphore-oidc-secret
      namespace: mgmt
    type: Opaque