---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    SEMAPHORE_OIDC_PROVIDERS: AgB9vDAwVWOM5sMxONN48JSGxax2qc/H9FaH0+VS03vvCAkWDAkHb49487d+kMECZfEK/qtTGBuL0hCU2chFEM3dTvQ5q9esWW82PMY7jarrQ/ypMr58eQUbDlkC6Vk5pdj+XxBNfvFXj9ivcTBJU0Fpphbqk5hFO9jRBDGq9ioWdLheJEAFPwvbFqrH/ff7z1L6etZkCf8YeUN3UU2R4cRm+z4u5InTghXeUQ14Iv29ZvblwQXVpEQIY5gfnaajJR6JzMIiAmcrz46FDwZbvzstn0T1gJrasSyGrikVO0ezXOCo92A37RSDm/iDOQal6+w6S70SIDbN0dibiSureSDjpLWBqHE9xlTVz+Fazn5gzm7he6+J3tqVeIx5gQQyTlDtDZfE0/E2xgSLc0rjF8f7iSBDMtG//YI33jkOcezd+WMZuWMZezmCdIT2UPvLw1VB5xnFNs4DWanMMlUAU0al21k7eJMUhFxbgdNJuM76f/QzaUyRLImpHRcaEvjCbCayDrY2B5skMW6c31h5iEDl7JWmiXDk3ZBlGaFAyPX47DgNPHstzlGSVVp2fRUxQfxq+px89/Ws5teNWGR7W3ViQq1+BmgabavcVkLlyNywfZKt+teqIBlbuTz0ZxksnQ2B+FycDouhi4Zcjk7x12owKWvQ88LahHX9zfXHSVJW0WpMWnUEOKNTw44IlJrysW+CY+9Ts5Ekf/Ky4cNGSexpd+lHUMPK0OPduPUTYftcZrQtCjspPH+0jrJYgtZHuI+Mpa4KCYzDTP8ZMW9ULZPaEpj4AgIpid6jOy4gJZz7/dc+4TRlYDnmBZhQjdcEb9AL3nZ2SY84uiSB2Rrh57qvTc6BcGlWRFjdyeMasWIJRK0hqGge/9m0htK+Ao4wbBNT/BAni1N/8Q95Ckt/MhCjxfGszw2YqnVn//N/06VP6fULdEVJCw0Rs3cbfit+XOAS+UjbabvUiqLJvZ1caYDX7OIxo5NjCeiUv+lJLqpqFlEgDka2TMuGJNW1H17knbpcGQKLPHlYam9tGqJo6shJMqyIS7Cad8X59p3uGnKUgsmTgI1lG+9KvII97I3sZkxiwFasnwQrXG5GZSLqjMGHCYEOecH75gyDaTk0MDahBzy5hyPVRSVCQ29WAU0nLPuyBnNs8Uo/ZP5sCJJiaDuuGg+WPOIbLn6O6NfIyeoOGbYnf+OQvbwFygPazrs865oWlz7wlALh/IlqZwLYG2N8I+grapWTuG5+hVps3j4kVruNVPVP7/670seB1knmUcNBmv7s15MlLIFfA27oE/z4u5oO5K0hBbDRSw==
  template:
    metadata:
      name: semaphore-oidc-secret
      namespace: mgmt
    type: Opaque