---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-oidc-secret
  namespace: mgmt
spec:
  encryptedData:
    SEMAPHORE_OIDC_PROVIDERS: AgCUCh3WQKLXT6abCdSb+MlSSIhi60+zw1d6Sjn0Ye3NzSx6mjrhOZTPJkSEskjWNIpBXpV1EqooccR5Smdd3O42E3sdNgFZtw+4ZGx2Zdvoi+PJyVrk/HpfzM/g6CWdkfIT4eMMEXLGWM4+kixkew5shBqHc2gVVZpou1eNLFNrdColf1LE8+pEIR8vSNgZalvxpqVvfpJT07VXi4lRx9z+s4j2PXsnP2Fd4nSff3MDjrFnCZLyAQ/RZFY0j56GchtjRbCh3TbJYV6I8813izfH6Gv+rG5zDhR8kGtCA0hAdZZWxcqjnAJ4AwLR2GMhi1Io9Eq6RPqnvEmz2TYv8ZZjd2eJAxcH6dfDrpwdyt3wKtUA4NRqzN3OfT47oOejyrs/UZYIJGvmr6++hVGDDscHCpK7mkxvhlWPvprxJrgyHTMTwGkpLDnTG6Zjc7KJQO3OCx+lRdJemnOPS9PjPlsa3bayYKqXG9fAqqURLD4I3CGEhTrIcPH8bCeysEV+WECLiWcYN3FedS4Wjzwn+g07u7DxV6tOLdzBrGYV1J4D6SfVVLTW7AMtIdtqLvj2nRK0IHGvDBPT48s07hshq1eUWN7b1d1tH0H09pWZiPrqALDhojTloKcUqXcv0JsDQBi+/I2XX8YPGmBc663eVtumTtTBKtWm2fr8IJ53QkHehZUBKxB5Nl5hEmO+JcWRjcH8VGfKkZa6edHMv3OEZ9u6AxqT0w5OZPD7qVjsQjqkm8hunEvkpJ2dILkrU5vuwcaBvKFYsz0Uw69wA7bTx58Ox8uQMYnRTqoWBIV9BH/va8YlgCM4RpdhGLf46jL41FTBnZxjCyamScSvgZh00bgqwpFP0jRwrMoc7LuPtU3k+xoxVlyLMTrWiLrbtUGBvgN16kcm9X7QjFdn4b+euEgRwQqi+O/nug8TpSxY0OMe2mS+Rf5JIfLVLr9mcApi+nEXXcx5VyoWkvD/LW1mLuh4BEIOotEybjlIT/zaCCJlT+2ksoWtvDhYyFDJZXw8DaqNA2dggzveITdJK5pXQHSBYGCXmlOcAH+LYWl4RnGGdmd8hqrcfLf8N96k9IDAKj7hZ7ljJebcD1NqvSh9qplQWonuGMe+jzpeZHxrK/Ct/sBLN5WsrqrrgjZsJB963KBS5GHi8z+1bK6VCakseFUuQCYPo03OcVh/+9T/uiHCTJdmzxnSFEzMEUwrxfzn30Pkl+BYv3pCYul2yufgDEmanZc1/gB9EaZfv0AgeejeSdxvAePXHSJoWn5ZDeBsXIQ9FNXJyRNdF5xJKxxKfUsVSDeh2svoyTxKQw==
  template:
    metadata:
      name: semaphore-oidc-secret
      namespace: mgmt
    type: Opaque