---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: haac-maintenance-ssh-key
  namespace: mgmt
spec:
  encryptedData:
    maintenance_ed25519: AgCCinCu9r/WiaZWctWv0eCfm+Kz0i2i1QncTji5zcIX/z9dU0K5mX8uD+1laikc1C/8ruhf5+ZfTZO/Z1qbwpif05/Nk5OLf+tzJpsWORuC8/ZXSalW2AMlOjx9BrKdwpQJV4hJos6pJrS+fZ2i4flUNBw1f62NYWZm9yaofVnRtLgAWYCWBGj8aFIsDvX6+9UklYyGn+2ryraYV5Qb5mHzQKFxw1QDt9cDUqxybdeWXADIjytXDONmudE6uPuIvUKiunwScmRt9VbpvFMBEQuG4n4UZENr9fnk3rwmh2WOJ+4AhN5WXbZYzq9ISq7QIvZ3qDKAsmbsT/XZFephP+v14x/pu93UuW/6KoAFNC5ANEnRP2S7XalciGA6f7KO2bDyAlcQsQWukx2B1DaLRUyMJmw7TVcvn+VBpAA4Uur/KhJMYGw8tKktcegUNYbq+5LYi3LJIOI43VufJGWLsNU8cVTAPwoeSgf/GhR4KSOvOU+GIAcseC4vxC2pDtwAGoFWdo/uhuFGNmFHFoFQyMobB1I7e5UnkcTVw4ABHl0ux1xQiqytMF6ExQc53jKzxVgqF9/yBhN7Pbm0WVLtzAqG7VYBbLHlhaYjTSRmVuA5HIWz7A/dkBDNJRYoT4hhxcyMKaI68MmQ0Hd0WjAtJHzd7zyBaYFJ/tHT6UJ3czqk+LnEay8YaubqBnuGLCDtTA34S1qZqKypD4n2qekPtaN4sPeQ1W9OCUlsouX8rLQ5aHyhJk/I8NJgNSzvb+saDz6D1udvQ4Yi1gjm0KwTU0Q7w3ueESBHJ0fPvWi0WdFSyQ2nMluM8GNpYsAY7R8jGeM/5LGu/AFahPENRKCsgrLC//4z26bvxzJJuJG8863PVidEovPnC+vfm3DaK1FjCiEvSLIoL1WSm5U/VDvJvT5fjihPjriGGiomu3w+4BABCkqcAlMPWiCEA2O2/zjebYLu0eEwAbdR2dyttEQO8O2a75jZfRgW+wzu9OQKrKKvNVytMtx8SysuQB9BJpo+Du8dUrOVWeo6+Lvx8eQsWYdZKqfr0Hq+8RCU0IrjULQXJEuGBSnZ3bGFb6taYZ8boGTnDcWKlGkkaWlbVINatVt4HAJ91shvWPFh9fAWgt+lXu1JDLoqEZJsm9KBJwMP11X5UG0A0EqP2js1SM6bVk1uK5f+5y2BEhGHTBvQ5dPFPLGHyC6+WkxV/nFEBAjXXGEHLa9bbCN1e0RJ+NNFi5hK8NiMHFaa5sztlpw=
  template:
    metadata:
      name: haac-maintenance-ssh-key
      namespace: mgmt
    type: Opaque