---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: haac-maintenance-ssh-key
  namespace: mgmt
spec:
  encryptedData:
    maintenance_ed25519: AgCDCQZFrvlTP+T2EDGvqnd6HxLCXaZtZoTxLGsnNR28Y0FmhCfilQK+E/IFWefzdj1Y3k7g9PTPMkJYqVQoPdMA1qvwQ0gifI+jXgMTULpqYMmoHsBEoX3PGFYp4w70opV37B83xucYMVlDFImIG+Vxdp2pusxVqr/Nt6hpOikz1uZc/i/5mbYINtyXk+J/PK/j+4JESzIdVTc4MPvd7TVN+tuDJJcH3iyop/ZpzKp6vebNXu8ghvw1MoTX2QgCeG+QJeX1zSDD/5VsaR12dHMa/mEs2l5IX2OxyT0bjdM40Q0rBS1GYkbXRYat7DLrg7V9YvPUhhTAZJxcNyATGbbHQujzC5Crb36F6IxBa92UXuW43PHzYxY/knDFnX6Q9IHayWV57SI2Zj0hpribbwbY8TLZIr0G71yIA7yFglLoL/4Kf5hfxROpwKauP/K94jV87+vEJ0bLq7Yy715wvaTpQpVwGwv7onP6gKHKR0s9HgimVdfH2uNPTbbKUR0ncOKgjOXphdmAjhOInCIgwwhbs6K7DObuO1rrNgqjiawvbECqN6TmlyAyc8EBPJVz8oNPcYFg0fWUvYYFVhCLS92+BStS+5nMSumsamwxa1gCmpDTTtJQs18eWXa84iL+5kQIiJ1R8RBcBNtP/ufbO35jyx41vJpJVpgOV/LZBRM1Ur9OtkzTfQ2ZlB5W1v8E0oERabaV6lGqTnIgTzU/ixmhguKYyo22sW1r0zHFDdGPIPWNXEpCkslBu+wkOIc3sRvIddEh9O+SpbY4qSwH+HUcRo4qry5AkImja+QY+Fj7UdIC4ejRCu0qLpKhqWy6xmgcFpB7tTP5DXPBBQAGqRsJsE9ZZBA8wlFK2r/tgGjiKcQBxi+kRmfY0cCgv0D68GkoZE6ZEi39xoVNAooMI/Z90Hng/uYbjywMpzIaNyUtPUGaNNtiegiuOXXs+JOHb/bRhZL3zs90iIr/D2bhS6embYT/DULzrd7znpTtDgc5qYJAd3x8UxmYy2ewnuvfO1uP6GTpgIjAIxFjWApL9maP3KnScSUvdVBkWE5P8DHvMlb9rHiTX5LBiZAXkUVAYuPiKUAr+x+w3qAmbb9CxMpW6BYdIWm9HSx27j0IxBuypX/icm5RKpdKY/xG0UG4n5zBvZHRagpeeQgQYgoXxbS5U66eLqV25qdVV9MI8v7yXERrERLCp0sSz5ZQ9z3kepYuGQbAp/HpvDmqnKbfgnxLTQajxkTYcx4s1WY=
  template:
    metadata:
      name: haac-maintenance-ssh-key
      namespace: mgmt
    type: Opaque