server:
  address: 'tcp://:9091/'
log:
  level: info
totp:
  issuer: authelia.com
authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/config-files/users.yml
identity_validation:
  reset_password:
    jwt_secret: "KQFow3VPwz6WZuWjLd3zIMx/Tfdkno+xi0DxhlEGGig8ZNUWuaLy/sR42DbJZMjl"
access_control:
  default_policy: deny
  rules:
    - domain: "*.nucleoautogenerativo.it"
      policy: one_factor
session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  secret: "KU8nN+hEOKwNduNsQgblS11YFJJYmAWcnDFum9dKIdbmSKlcYb/0SPBjTwaaCSr/"
  cookies:
    - domain: "nucleoautogenerativo.it"
      authelia_url: "https://auth.nucleoautogenerativo.it"
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: "GmBCGztDNTsjdzoli7vwDYVlOphpH/mKmaV+aNdnUT9c5kNBPtPIQoy5z4ILnyEL"
  local:
    path: /config/db.sqlite3
notifier:
  filesystem:
    filename: /config/notification.txt
identity_providers:
  oidc:
    hmac_secret: "KQFow3VPwz6WZuWjLd3zIMx/Tfdkno+xi0DxhlEGGig8ZNUWuaLy/sR42DbJZMjl"
    jwks:
      - algorithm: RS256
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCxJ/JogXQc82r4
          eXZfWRIJLfBOD36+r8bj7h6HpKtlSWD+szI7KAK9jLTQk+pOaaUpNCKy1BzxDZKP
          ap9Cmtn21ZV6Gq4p+BxxnDvRqj3lnXJ+H3Xx/C33oWPy0DUwxRXnXe6NDIxqrRZF
          MprmTfeeWVk7ZugyOK1gEUxBMI6yVlCtjpVvViQftCXNa8Ds0+Gx+QskJxXWJIWy
          dXJPdAhGOpYUO3qBN+6DtpTDWu8PxCacVyAnMMKb3G8R5V4CpT2bK0MknXaWZxLc
          CSN3reAaP9YxxUDyCOvJ/Nl6eefqUbxshc20n/7nxb/h4651lHgUE182IUNq/+mZ
          0tIokrLHAgMBAAECggEAAzzKpkmaA0luLq+cOoPYhjMWYtF6VyZuiQ3PSwVMXePT
          EknYuidcssrBJyqngTABuli0kEtmDVWv1E/LgfPDK0qd77GlyyiN7y7pZ5x9LcFh
          1+zf7UCBiov4KqDOyAm3VmzAsPKGF7ulXjWy36Xpx4q0dxcbWTJF9i0lapo7kVtm
          Ag1geYK8vU+22bkjIW9Qm773nfXjAX6G7RrSUNNoXHQF/9nZgh6xZmq2lnpbcdR3
          QVMyBotB5KJohM3N2jfIZFkb97PpLSdiYBmr1FtJwr1cfKdW/sPlPlaO6HR1F3Em
          Gg6ViyCdCM7X3mBD18v0Nv5wwc6D9y9CxyBPI9X0sQKBgQDWVEtHYMJe6ON6hTXS
          pMkaNcteMylIBOXMN5bM5YnKKW77ox3vgKYSejCwWaODnv/jRftod21sW1O7d97k
          oXmjOe/g3R+/B9wXEH1IWuOCCfUCVuQs2jjSqvmDB8ih8lLeeYffCmIwd3N2vqzO
          6AjD5sf9md+Nqmzbion8yuzB/wKBgQDTmXKlAWwH5LWzvRAOpiOQnB4jBHo2i05z
          u+c/rGD50FVf5sflNfbHx2EOH9ekHX60hshw2U/2KNCPSkyWBGj2DNYkVQ3zv7pS
          nbkLDrqq3WTbQwMRgW2hFjhv89x57mWQYrUO3Dmjq45Y1jx0hdKqf4Tcmw71KEP5
          0DXAvmJ/OQKBgEgK64bhmlQmuhf74NyeMU7TGDngvpaLtuaPJOxYl5lRlhGVgcF4
          n9oEIouUheb/MgomAtzZj/llNV8FavG06VsZZW1TRpGCxdMm4sXIb0LNsAKKTIZb
          D9CYUeheXG07M+m+NhKdveWGsVQPwayGyDN5Rm4TI9bNm2usRLepSi3nAoGBAJWj
          LGn4CXfDi6OiDhrt7rSzUrSc0/iCp2Y8+ZoTwzim1dlOEQrNEMnS+5XLeun6WcI8
          lr8HTv7bejH67xIf6EIobb+fzpAThCYsl9F0BxoSGuLcDu1wRCDo39x77ezkZDqp
          MzVhE/nktnOofXRBtusP5ttDZF6GrRua3IiDmpAxAoGBAKTFkr1YgGOXp0KCyYWS
          vrsS2fFBgj6MifCwymnl2y353sHbbxAnLCF/q+MyeHspKQyV9mD1n8REtT8Wcbob
          R+rJUVShLIygQJf4jr9O12VhajsCGgR7pDf5syRoWKrc68xw7jnJQv7z0/UbmO4V
          8eWWVjR2trxDth9aoCxxjJTt
          -----END PRIVATE KEY-----
    clients:
      - client_id: semaphore
        client_name: Semaphore Ansible
        client_secret: "$2y$12$rJqPg06/wKrc9TZB0UqEq.J427GgjcGtgD.3Oklb5kRwNSG8BzbJK"
        public: false
        token_endpoint_auth_method: client_secret_basic
        authorization_policy: one_factor
        redirect_uris:
          - https://ansible.nucleoautogenerativo.it/api/auth/oidc/authelia/redirect
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
      - client_id: grafana
        client_name: Grafana
        client_secret: "$pbkdf2-sha512$310000$7n.LWzAeFyN91rRYNNErwQ$.RRt9QTANSlK/OtNAMYM5Pxyz9QtmqpOfaxTThXWnFtAYUxhAJ.BUYlLTD1wFCQTLb.rvmWamO/q2BzVXg0baw"
        public: false
        token_endpoint_auth_method: client_secret_basic
        authorization_policy: one_factor
        redirect_uris:
          - https://grafana.nucleoautogenerativo.it/login/generic_oauth
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
      - client_id: argocd
        client_name: ArgoCD
        client_secret: "$pbkdf2-sha512$310000$4YvE7ZOvA3n4cOfApDGA3Q$VDlb7DboTXrGasXIRR5IecbkhlsIIQIkF6Vmq2lsKBg1aCHJ/4jQL5/ac3F8CsoFozvhFFmdtGAbUdiWyGus0w"
        public: false
        token_endpoint_auth_method: client_secret_basic
        authorization_policy: one_factor
        redirect_uris:
          - https://argocd.nucleoautogenerativo.it/auth/callback
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
