---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-admin-secret
  namespace: chaos
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBt4klB+pTZR4qmbA8tx/I9/XVx+2m8jkWvbyMQjeWP+s1ToMuhPv6EP0rwzoE3Pab0RmlOJ66JMu1+la2KG8PoRX2+05VMSQa+Klg7NFUJhphDtofckyeLO+GeM76rDgH8XxUEkReGLA+bTM07lIYl01IhF7V0oY57Iy+rG5TplpN0167e0iMYKmEWpbTcvkVYw3pnT+kQglfOGKlJuGGnsgqiINq/ha+enBNQYvA/jsZTabur9UQ5NeEi+5VRepgaofimOYb+TRbQWMWAEFQ2d6lW7viMYVnzv/wHSR7HUHVIUHtf4DcrnP0h47pICwVvGrF9IR0KSmPKLKlB5MLmZ++Ba6ejCAoFmr8Xs9gxs90wLFV/mBUAOq/5LYI40k6E6SJSVLBBtQBWQJ188Iu/i+GEMXwM6iiNXX2ImdzvvHFbDt9X2tA6SfHTxRAvQF8lKI9bPeXoxO6x21gr6f3j7plrPuxvUsqe/2iZ3y33vnVi+F/P3QwY/TPn7xYlP6mMDCjgr8S65bA4Zwz5cxWgmDKdLP/Kx8Bjz9CpNByT147fHbzvcuq+YhI5dgV4GZjAWTfo6ZNCEM3OIP4adsDSLnSJQVNBLMYPivAyUXEdWH6aC3xCNVJMDobJN426sE9YXgIviMBKOwbSXUv4I9PVID/Zc7A0NkER01BCJjz/O5A7Wrp32QuRuRE1hTRNDs2f4tRseM8LX402X4u2c1VmsCdkNw==
    ADMIN_USERNAME: AgAi48bsoaL9OdXoCxAkHgOjZtLAKSEGUTf2uQGSp/imVLBrnD39cp5z9ET5JA8qwF0P/VuoHwZ9kTg/qpFZros/d1VGFuC9LcpsIidRTdtaVFP8TBFeGFhd8HjitgEuLDcARn61w9/1o/e8qjoAyGo8xRFUGQcGt+SMcRHWopAHIabZPx2N2voULaGP7IclZZaEn92kS8ki1+kSSEvNbBO76/ufJnUSQtOY/EwW9G2PuHIO1ptgTeBebN0pGkihf9LWNUo2UIdAFnydm5arfV0cGlB7byHs/irS+EOyG7hg/4KBTEyplD0Kz5i3iAx1tqhUyfVgPpqkZqbYCMuxIv5jGiGUG1e296uxeVkMaJm8kw04AR49/Iy2/zJ/drxVueO+jbLgHfKESyHEsfxBhs3jK7AR0xi/UDTCeLNWr706fDvnabjMxJ1QIKSJExp1j01BZRBX//9iuk2h/teCvIjPPSnsQ3eBSGFkeYVFNhkIUGOd7CDXUDTeIwmcsqIutgOjRXEqggmrnlEdvTB4pu5Wv2sFAyeHZC9ySlpYc3SjaMyiUm8nrINr1NOTyEpMZj+JaoTsqmUkd024ZwUoX4HzjJbiwLoAH2sCzzsSSPkP5b8P7EAJE+VQklPdAr+ITb22nN2YMKaaf3o9kF1iKk9HWSmOzXFlxXNrlj3Jb5Df6xWnQqjpVkdP783el/mCZDkvksRq5A==
  template:
    metadata:
      name: litmus-admin-secret
      namespace: chaos
    type: Opaque