---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-mongodb-credentials
  namespace: chaos
spec:
  encryptedData:
    mongodb-replica-set-key: AgCFfXRaP+Fg3GW76G/Z0j6ZtkL0SWzwBFHasb4guEkaJ6wutlFU8WD2MQKm/x7S684CuwoPyYMPOzgFdgnE66kV67IbZRIFf4F4UzUhwJU4olsjBLLNh9L2KiuJIuFd59J+qNEAWmTMvZdnRyK644P7OjQmJxDnUdXWx0QeMSDcvFPTtjmDjMmg7PTZxr+4Kk4cBnb/NptUUJyj74bx5x3tbmrF8xuJC1OfdXxlPqpCuXO+eevwBnB/Dz24FA5pM4JV7kQb36p8Vk/vUYkYmrKIokFsiQof8OgMfaknyBjkFs+HTwcS7FLWDwOITYVranlXeHvLPyfqVXbbyBcQ9Fj3EPyXz3rDpJrOzfuR0lZnBjuy4LjTx3Qk+UVQFP5Gi8Rgng0ChuEbAEbLKHbqpMRyMxdkLYIHqTXFOb086cl4xDJ5FQO+XqdcCysAqCBVUyvjQ4h9g9IFsFjng3V4ewIvwL6Ow3t+sBT25Y6CGYcNqsLGIwpu6h5lq3dBAConFSvRTCOrqkgrZYEJz+UbyOH8RvElwzefwlrrvgXoCkZvmJpad4TJtw1IG3GLU2P0Z7BIluo0BXzh7PAPGwRKOKpo4KmxLmRnmUr9avZTH9Aowx+vUODAdlsG4MkBdryCqyAF5wpIwYhgQqEm0D6LZK1ZVw9kxl5z2YOZkInrupqUUhObx2E8zeLGX/lNhNjkhVBAiOiDjOb9HwWs
    mongodb-root-password: AgBuu3LtoWPlMj0+YlsFSqG0jPkOzRDrjs64OkBg811GEVEKU08whriqs4S9AUdGEeWHGSwB7EkcAI/Ef5HWZLPCmig2mQCbX5K41Gw33eMV9iDnvL9vbn/nXHu2wryuX4SJvwvb/Rbxe2d3qXl9EsnE7Fozo3SWHk/1Jms/Cj2GDv2owpqFYkMcms9tkGUu3FmEt1o6+FgLNYhYAwUmwSaBoN3ts5Pa2xciUGmg/IVxzET+RwIk43LjmWCFw0OelyIj1ZSGT3D0FSUeglDyG4V0iGM8VtsGqBlxRYcW3k1CopEST1RtcpzaDZ3JOy2EOxoLf6sDYSvcnUy7hhInIKnfWvj5aVFeq32hKUp+SmYkw8tRyZisKQcdNmyiv/j1OtimNU9xZ3+Ev7ZlNW8oiqYdmKmFw8pbKXbyyxcIUNUbFD4kwoPVdELns+1/kWMeAMu3yOmucwb3PiOytmsHLwWK9rfrBAfZLTWE3MjwiOs8k2Cr3tCLz6rnYYJkHyz08wqOjfrEkDPzcr2z9ZW48nw/wNla2gpjYSS1IoUFf6ocUYHKBYZcIDlLFH6WEznS2zU6i8V0vmeTxTzGuyKzmXSw+fionvJdyCnUfOpzEPiYeIeRP2rIiyfw8oY9Ct/w5NLH6zVlJ+CT0yR2IKEbiU6LVm8xLesI/x/pNOUlzWhoPlwdtcHH5VNXxVuU7Zn/78Nm+QeX
  template:
    metadata:
      name: litmus-mongodb-credentials
      namespace: chaos
    type: Opaque
