---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-mongodb-credentials
  namespace: chaos
spec:
  encryptedData:
    mongodb-replica-set-key: AgCnrQMgor968nv2oWPm7/SN3uAwx+s70JFj66cBuvUADESZlYEeoDzCaqOc7oG0GOyuEdWbP/l85A7ci49hXeg5884Ut78DU7qFlsTHP9BX8lhs9ISFiDwiXrqaDXv6rADo+Z3uHjzg9VzG/EgQ2N4bhcWugHa0Ay2V/K8nh0qXmwlrEuHv2X7r4/bvQzbgijvn2LmjL+XdYrC4MLgGxNGokQmYn5EqUhFnyIncUFEtOOGihX7Ttvho5msyB+QOQLOx1nQNFQWD7hnagqbCCB16TcHbmxqycITLhtozOswXAPQ0gZ2uCbxEZvUKGed3vWAEl+cEcefS4s0FUbmbeeTdUEDNXOSkVY4kM14M5eaESCbmUawMiTPEUdEswL7kifjG1HZPU9BfbAocBYzZMShpot5vzcwYRXTTFQi/3j8HMk6EnI3fcLnM4JRACPD43IJrKuFpyqwVHVIaBxy5w0AKf3oVluZEg1DABDm3a/+YYKuR1/vyGHxR5m/Y7qfpGm7DOMETdr8af14HEXLm5d3zHVZFwCEW1nHYab8NlYoAZCRjq3ZDA2M5MKRbHB53mgAuCnG8ntzGINjbQTfXMS2sBSbKRnae7/FF4/4g/ZfVBZ9jTWAtBub1IunfNM1tctF4bGJYmSW6W5fwi2h4ZzTT6QoDLP9hTZ2RMdd6MrvICVWqNAfRnn4g4ujyBvPje1q8YGbX2REsIy9S
    mongodb-root-password: AgA+auNjqIN199nXQW3gOCS8745dcyWTPlnbAAv/gusjlET61qX/FG3KEnneAZ87hJ/cxU5r4aAyBB+PitZ6HK3jMPhNEIG9BA9L6hxiKmkZMa56Bn0V93DZw5Jvm/ISJyZbRFTafox84Z4mQ/EUQinMvtsbxSmyBmIDFpHBVcbpmFRyWicQa8zKwmHWzsa/NW3qCvmUXB87+JhAFZ3dAKT/2SDoiwUazO7OxmdtCELw84xUfNf/uYoBMiBlqh0Y9NvXj1zid95t2+Nd4PUwHikNaoJ7UwwgpCITLH9TFCQvuLOJaTWN65oCXeWOjWuVgy7DlEi9V4shPVvXoWeidTi5/JCNP8/5e5T63s5yf4mmdrykXcrgg7NSIkw5lhywukI2fVVT91YvdZo6VD6tP8YUFzHHme48xD+akFJa4n6qiYp+uYNP6BkUhL87Zcu3xRkobDiYeGBt44QP+08Ovaq57dXJPVisWvou6UEXltJFC+nDu1svogDzq7Zn2Ge7jH45ALtUHVLp0q3ScdSXm5aYtlo/rUO8mkD33qhSs0M6GrtjXs7jl8CyW62lPodE7Oxygb2FfJWDaE7K7v6TwS3xGc9CwgkWnSFweJJZa/LISE1eyGRifUOREtn8nfiqscXXPJC1eZdgm77NZSHuhVmAw+Ld23z7nwLLgQPSib2rFE8VoXKA2vU7n/OdklCPSQAZyWEt
  template:
    metadata:
      name: litmus-mongodb-credentials
      namespace: chaos
    type: Opaque