---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-admin-credentials
  namespace: chaos
spec:
  encryptedData:
    ADMIN_PASSWORD: AgAQ39R2Iy0u1m6sRt8pJlkuipTLo7dpXKw3565L0JGmsVjOLvU85lg+k7sIQx1rqpG4OEtJpwjeJdxGgJFw4HEG/JvPRQB2nqS/lwz9ZyWtLMkhaNbl3UbwxDPtD+SlYleTOtnEQBxVwic2cQcE/lgcWo90o99/ZiBRPdPDjRBozz82NM3Rlof7WszTelw49wfpISuM9tu+X6tlFw1a9wvRNMuBASd67AO2fsP1SZLjPup9iJ8Wf3fBXXmYPcVdf9npYEl6LlapmSee7R8duGt7GbxcqHscjgGRllyvpKJaegh3BoOUw2yJ4b5toe0YjNXK7IMHAW5E++x0hXdKVvcCMPU+27QsZoZ9L9lUWfdlirsuVIPdNt6+Sfs3EQfxVj6Dqf8wJfukOWDTXRx78MYbDE/bQp5XE3geXKKP76gokT/YfV53L4vSXlb2RQhCWvMAzA0Wd+0TYldOfh5urMEvZtnlsS71TfAhW/QYu7vfpdvHykLgUWYHAWgFJgUx8Y8WJDiTgfMcB0iJPEv3CLXaJflfYVwdG0C3KPLVgdJ31emkl6RGJI91HhIkltq5mN3tuvi7xNaligut9qt1zKKGKRDdnmhArdZTsHKKS6z84UTnZRQDH0ZoME+dd2xzpYqFKOHCBeBKWs+ItgJXZonPeb9Y7Jokl3QYYLZzHoJX2nIQIMNeouzws5ZJXCYUI7dHx+wzw6hqK3lsn4e5ALr35SFH+w==
    ADMIN_USERNAME: AgBnvDkqG0Fp8ONSTvZphIlLbOqxSl7b+NN5KNEnu8KzGjiKZBrZoMYd2STqASel3Q4G0WVJFAWKgUVww5mydUpsD1PW1bGqrZpGaedVhoVvbH3ZhEyGhhrmHqYKToLP5CKYyRkf4vkIPZs7OrwcoD5jaP+qCjlphhbhxa9Dv1WJ2YB2eTVeBgDLkzF/znWjW5ZSVwnl+84zZK0tD/Xj4WYvjFaSFB57B/uzfK52t3RmBxri/H4oRlkzioGlDZmLqxA0I41BzsozeOXF/KfHE9jbyqOSXzCzsm9e6e3ZX19Dwi1cmCG6EzQ5M74t10g/zP3hRyyH8FU2xcXPdX1z9wi7dDmNW9M68a6vPaS3BnDceATmVct62FN8cc02nEeyjiVZQJKXrsNQVMeL5lqJwxS/eRoavugSbEBKdk/bqZ66yTza6FIVw/pFCksiqMkVkXiHDkSBkJ9ZmFiKP7AOaHmeHbxKj+kl5rEjCYlN2WQxDXtVa5LEdxKXUwNxdsyHq/dw7Zm6igZx/RTCCqSiSH+HGklaO3ieIvgx/pIjLlaO5mu5XDPYqG+dQpFRv6WNW29kmaTgX8+5mq39pPik6ap1Kct5/cV2Z6PFP+StvbU+ulVCDNOZXWVVRxbzVPVCwCzxmZhPGHhmhWO4UO6H60WyDK/+md+WSt7MzTTWf+SdcBNb2YuA3hJBdpnUCOJ2NsepQj41rw==
  template:
    metadata:
      name: litmus-admin-credentials
      namespace: chaos
    type: Opaque