---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-admin-credentials
  namespace: chaos
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBp63zm1ntDwmoNRKueA6RO7WDTo09FBqt+eq7bclLkcwryPY9W+820NHNq/PduDxwBo2b+DY98gUiwfqjKyRJQH7vjDR5pjfzOJ6pb4fG412+tQGxEeP4J9B8NfnQ+iJOaA4U9gMXEMKRHr72Iqg0+huZF0GuImY8j4skYDZ6knkaEWjyuTmTQClWc1ZSQkPuXv+DhnnYyLPSNbd0r1FPF4uh+qZPjUp2RJK9ublcIO716ZuZgI783ccY5HCOyWsh77ennzeyXj1om3tBPdZeLiWZ3sTBZahOPR2qDs5Dd9pkPEPDC5fLeintBV3R5Raq5SqdtcW/7nwyB3Scx99QHfOHqnrVpJxfTRJWLaLxiFeJGBAFa9tng4/PT8gvVm18CK3vcuaG900pcB+fuGgabgbQtSm/LdQMZnRUQOtz4SYTlG8WtmwTZBh9+7ZGMwkIFpUpibfu0ceN58RikpVrYvxjDe8JOPFxwq644RJMo6cgr7CCTT3wkMXYI6OrCgW0Zq3PxKFiW5UAxPe5hbq4N5dHEpQlXdRzE9cyIr1L9KYFdEceD3vDRSEIZH48LmEtb8AdIxvu5VpEllFQTp5B6RDH90yFCHRvlKoLXKNm2MjMP3tWF3y0Fb9JiZfg9ngctwmJQa+LAuMJJRtDRvd1c4UEOv8JX4eyyMM6mn7NjqPs6DmCgkfu7/sv4pgTfUHzgqa0NKOUCv8aHMty/h0OwbEJL3g==
    ADMIN_USERNAME: AgACY8B59iaEmwdd3iHOjmApLkYjYiflOrf4IhcNbo4uJHkA2d64akZlmlZ1TxLJTROxCsBMeoQzWj7RXVnzAl8CrpQFd4yhviE8XYFxYv9SkYTc/PzO3JDR5osiO4DmaUs1ZADXblZ/2+u3UcU9xyr0QVVgV0DTkHzyN/je/ErlhNijolIfu17wFEKjz3ghEMxi1J9ylv5fww32wi6SQqg54sRf0a6Dvtqm38pMC5k8ec6ieOajCyXR5Ap1jSt7WHZ+Pb185IbI9AUTuyDHaJbyfTxOvao9arttM2jv1QHS0ixJp6o7W/IEf+pOPuI/y+Rd+DdjOTEygrVYBY0y9tzqx5Sz7xRwOR7b0tahRvTmbBafUHmQu/UGCiH11T2eNEWOs8SGpAs2yRghj9SWn5OEHv2KIAAzDrwWoXCcD65WH3b4m0yTBuFTX/sdEkKW6em2UuegL3KmonW41MIPBQqSEyXC4q7FQlQCo+hDjGQMV+I7EfAT+Ne9FNI8ef3TZY5ZKsMujfCjy6rCXb+w6Og3vEQD/T+NWnHjkvV6MNRSIM2uU3scFR5RCXt8MnzNyUCajj8EMMT2ZpH7LpvowEb6JerWk21usUoevgGsJOkY+GYkELRJOoPm+fNWaeqnjf/fOHSPiXnq8nDRoKJO3o5ba9TT8j0+Smbx2ziFcC4sQNvwwqqpO0x+N8r1uUNg7ZE6X2xmeA==
  template:
    metadata:
      name: litmus-admin-credentials
      namespace: chaos
    type: Opaque