---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-mongodb-credentials
  namespace: chaos
spec:
  encryptedData:
    mongodb-replica-set-key: AgDGF87tXdyJ877prEnhfsSJAP5kYh+LU1hNZ9Rq2Ragq+EwgYWiTW9wYnbIzjBeNQPHsLFUAJSOcBRgkiLK1OSwLWVfxoKGN8Ylc8JCsF+b0QUeg8rJe3I++y5ZkSIPf+r+VLMXHIzycdYCj0JnnOK0k0DzvPUFJBiQD8E90k9YB5jgjzfx/9Q10l4MAlI9fA8CUU4CQyicZHjCJ+abhMXTpbrh56JTt7Wkz3k65fItCL/NcDGbPAHjusvcR31yNOMb1x5lJEduePxRew7WJxPbKj93dTnwQUrrpyMkYQ2xYODZG6xdFMDgUnSMB3uO4jW0YHE17UFZEhjNPPSXHqbCkF9Nb53zHwumDtoyPihCycTQ9YECZWWiRZDk7/WoXwHqVSmPF2wmsjwS1/hW4bon/SOzWBguHSTTS2XKGcuKWy6BZdE+NQmRSNromtPD9Ew9BFPxTJPv/aHf9HHIDe80geVkK3FXpaW4/Scq8LJVwvioe5rlMMWHOdp0RdLsfUsurqkJgLL0ldbDh2Oyy8HiIHWbjwBgcNDb6q+HjzC8SSnHcEIaa0SEqn32kl5K0O9t6gd1Uq48xRJDyH8QE1CyrqRxDa3S3BYKQawV0zlLVAaPeyI9y0IiuMKcWYUlgdhKaI4+bCHb4fNqk0Pah46xl7bTjSGzXgEklQyNzRY2LdL1BYjCHYdN18iqxpjvsDo9EPUBbWFYsTQq
    mongodb-root-password: AgAbQIN8v2g/QZwewzHlov0ZDYx79MCRymh+DQhV7qX/6wJr56Gh+FT5DmoXY72/9WQHMeZe3AWam70bj+V5FNXGtN9RlmevH+2rjZmJnWDaUpqCP1LtTXnFWEyXNmtIAo5suKyDw8srUJ+lyqBRgYC7aAsYCalKCKs0zoW7wC2CXUc5EvVnSfEKbf+dO09YtO4uw5QO6g40/KupiJJ5mSleeAAZa2/mRqXFzgugRYS332kCh4Bp6KzC1scJ4GTDx864H5K7o1Kxrq2oJutSqC2YlrqVuBb7L6PDoHGVR1BSSNmvk+lYXLVZd5IzTUuE+bQvLtERIVyIVmyU8Z4PVvQIHrKBzfCGAticUoyeD6NA5xs5aJTWWxXo1EFQnUWkKEbRpKgdcWuFo1wr/X+caQX7qQN6ZflTMXepQ3nakKlEB+taQtC8znp3e7poKxYghTC1SiLSfCARwaLmvpQfRxye/gMYh4wGQVV/BSxLgaYvi3juT8CI47V1W3N7CWfaz5MY3Drfcre4z8vuv7qxNz77TZzX3ue6NdNTlnQ91DRjMwZ/PoO0bizKNu/tErRuZFITsqng45rJmqfthr5CbGJSWd0nDeaZ+ZOdBWaFjfxARnewBI5v8ZvwR1UwS8DO314SyRdAEJIJLAEzYon0tdFrt0YP2q9MS3xctPfnYRxPUdeVtpVZzVTfIBjmS+Tgv8Er5meI
  template:
    metadata:
      name: litmus-mongodb-credentials
      namespace: chaos
    type: Opaque
