---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litmus-admin-credentials
  namespace: chaos
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCyT1QnvdKOhCVhZFLhrm8dNGE/gmQH/J9gn52hW4rO0bXdxOnKEwx/N3Sj4/GwTMTjIXyhpabHq1pfdWLVPFI2dXTVVC0XDwjuffj+x8qBEyIvf0XlAITXCJ9MAPYN49I1oqfPEopIwLTUNGMUKfQ6iK3n5byKeTcRjz3UCJ8W7POI5kV1GfJydbFMZzl5e0kpahRAM51FYuPr25NQ0TDxcQ0BM/CF/Lc7hwoXUrTOFwiJSNaGeHPNXrZ+TL4J7Y3gkTusJWxF4JQj+cLcV+YLAns4K0aNIAWhPtNexLrP/Vh1wmzLJJup64CO+8WQXKvGo+6npeKRvjKiy0S/+HvpTVyipgFRwif895pVJwPXed6L456KnL9yIi3e7C60hHsQJMjQ/+PDXKwUv4CAfKKFdRnHAE3mqB4fH3lwrlAkmVh60B6cOoLpYxJiaXBnmUCZ4/8OcikhDlkM5KsweGMSOlqGdVlPWXCCndEgXE6SKqhfJBN8w0GZTVIWV8AhPZaJtSs5EC6nKyMneWvyEV2X2tWy6FRZRrDkAw7+Y090z+kiiST82mgP4DULc1/Ul0MgcwfUNKuSr7GuE6G7BRI4ALPM17my/LeG5PQl4z1r+pGP6hQJC0JVzVcDde5EBlW13iPWyi8n0Z25YsyyhM6QsUolL/0tTGNandvzvqA9ouq3quqlik47SmH6zRKkclsM3WmxLXBQ998Hv6HJ9pFiquWuyg==
    ADMIN_USERNAME: AgC58yG06xtmPjkVhKIlaGdtDbDncEpGv+b22Q50vR1EqnSj1UII6aGJY0ZzHngb2YC4dkXDYh3RR3RFbsm+ORHFnEPcJS2X2kKgHnwvapC+/IrDTH6EdnNgWvvAG4Y/1UFJHomEfIQgVkBr6/wB7ZAj0+P32wBaOpqw/UiMiQ1k2/fXPv2/BXJ1mRszWlAZhC5GiY2DOaW6/3LGcUieWlq8qkp/xijDJFCEy93+k4Y2dDYEJjZxAEYgB03IVKKo9c9Fk4rYFNUJ4Jz+8GJQu+qqcnyt+v6CqCwDs5rwfE9YaHF0nEXGaCsa75QovgwshGDh94CGNw4dLa5e1CqtmJwbAHbRlXSVmIWOCfiOhCIK60+kWf9Ye3SR3UqDFasGeGBKTjaNY5KE9eFpWv5k3ibQdyOaotvRR8MjYdiMMiJYMSmCvBqmfRuCvrp7NdC4Ec3IpB5ns9IdeWU/feQ0WHgY8Od4ifBOJnNjcsid+r6y66CvxfkJ5eqfdXmM+JM756GQepHZe3KisVeAEZnaoE3rUDw0x/5Af4nhhdCktYegRRoEdlbsbtkRAzqQZB3cM/tXpuVmp6Tnhtbc5qIIetbmOAc3UXr5lL5vcttTt/ZmZlsEHTb1T7jiEUCM7jcCoLjAMKjrwArUcCAozoKRaSQdd2BVRt23owsHNr4cpZFc1C2PLkYs2gkaJWpsfRhwtUMZ5DUBwA==
  template:
    metadata:
      name: litmus-admin-credentials
      namespace: chaos
    type: Opaque