---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  namespace: mgmt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-permissions
          image: busybox:1.36.1
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: data
              mountPath: /config
      containers:
        - name: authelia
          image: authelia/authelia:4.39.15
          args: ["--config", "/config/config-files/configuration.yml"]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: AUTHELIA_SERVER_DISABLE_CHOWN
              value: "true"
          ports:
            - containerPort: 9091
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /config
            - name: config-files
              mountPath: /config/config-files
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: authelia-data
        - name: config-files
          secret:
            secretName: authelia-config-files
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: mgmt
spec:
  selector:
    app: authelia
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: mgmt
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`auth.{{ .Values.global.domainName }}`)
      kind: Rule
      services:
        - name: authelia
          port: 9091
