apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
      - name: copyutil
        command:
        - sh
        - -c
        args:
        - /bin/cp --update=none /usr/local/bin/argocd /var/run/argocd/argocd && /bin/rm -rf /var/run/argocd/argocd-cmp-server && /bin/ln -s /var/run/argocd/argocd /var/run/argocd/argocd-cmp-server
