---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBMJ9Z+yhF0Nq6ZRyJizSk33+n5ARy4FbYuUsjaxwsnXQbEwL449FzPgV95Xz66gPkjrW2R1p1ZOjuZMPzr34dIqu3jbTknu3KWp8k09cMgQXJgWRwxZwMfiXmWNVJgzWmRkV8YNIpu4vFvfhdMybbX/g8jmOyCtMl7kCB7+v2cyFOqJCEK6t6s0vUhfxaLNInUy0Huov3JtUe2MjLMFK7Or+1zgQOQssx0/n6AuJ+gA9i14E0WodJd9JPYlhB+Y8eVIi28X2Ti1iNVOKEPdhr7L5C0g0+kG7epRa3qM7MySTuMDc4yjo/VLHcfSIYp2HaFjPNMc0Nhyja+6LmXYrlLml6q9u1zTB12wBmqOXpWBCNndCZYBStgPf20rhKdd6M+f6IQBgdYhS6pzYcAN1hHK4xoZqYtnF/Zos2E8HVEumufNBEMwxnDLFteQXjvBGwUP/M3CAdDD+VEztFhNvitIGNpMYMyavzq2iedyI+FV1NOks48iCwVtPxeaj7jRPq+z1awvn5vbdyss/HbxNmf9Tras+o3WWCk254LrVCJuyXTvcWrYl2A7j/zgSCTW3ixA1P2aXYIIUM/ERT2si8yf1kLW8+fRPawpUZfriZoKJpRgyHphE+Ebkaq3CMyDHg869wDAov/aY+peoEJGajm06Vnq9zm13XA5Juov4YnCv+RHAAn3rbF0sOR8J9rBXKV3xLjjwgU6HaYbGW5GTfhxPVXiUC4HvpW/Iu1VsFC+sKAb9lt1fYywII34KZEYDT9z9CMtrWBTuIqTmPmg6OM
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque