---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBhpathTG8mSie3sWE3WD6zGvwwRdjneSMuvq3kcBalDMOrb6PsnRkdVGhYZ/t+HX1ZEtQyW1c+vLldnFSCldBsq72Ij14xa5Cu97OK+s7MIdm2r13PsEvDpjOMI2IsKBATAkLFv+9QlAVHVQkZQM7+p7Ftkrj3zhqi/poOCWGY53Wc+722C85TFFEN9KCakAIO6oR5jajoh3cMbSxgl4Ey0uvZWXwMNMZISJdwGnvGhsBaZBA6cZory2Jsub5vwLrdrA7CtZX55kML+UsGas3bXh16w2Mg+OjQY08RVUgIIUl6FnqMmlmK1WAraCczLnyrHHDNkYHvawtqGrcbHjusG8LHChIe85ZgmC0SzhVOx0/b3Mj5/dPrv38YtLgQ2ssTBebbuMLwf5gxVJV+sOKklurcu6SiQN/ex8XNjFxp0Rdv4yTOP4iWj90zU89qlrbV4/CmTrcRHzARGTeXyPvYW0xpKjNurbmY5bsV5YLyKHnuYdFJJ8y10paYTFjpGqoj1Mp8D0UxwAO/SgvQo95Un3JRsXt9fEKoIyJjqZcg1l2Xl4EZUwWl2wjJi2cRonjohLv2WmJJu7ScOUdOekPzhj6sKjEPQfFsIhEEeV6s0tRWyIYEL64qa9Q0ecUu6YMN1tlQiu1ChJBdbA6gLx1biDUe9E9HfcLcb7lFll5+UTvZH4K7mah6XJxITV16w0RVJyQlRzeCX6p9irv5uaZmgIK5XyBcdQJ9nljHcqNl3uFlykioCTuvRQzY+EWeJFGIBqwzzt3pFCOjQeCy1q8F
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque