---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCXIq5AeUEj95pcIjPw/8ZzLrXxvNZUyRaCYqJJ2swuoeNJG+QNMJBjWwmHRd117JJTdAoOpWKBvo3lALmruhxwVE7AjHtv4xUCOt/N4jq5glSXefMQCjrxrBhTcDHbG2Ns7upomnIkke3S/PIgj7geTU6GmTl336abnMF38nU+LvOsTYCFSIWCVgSEKi2fafF062Pi9t8pH7u41oR7cbmI75D4VoBnMkIK8N40N6cppjpK6H2PZp3H21vA6LvFwcLIFQAnNun37VBoe31ESSJRgud9tdHCQ08eIna6KUgvvCG3RaXb9fQHC8pg1z3OkdsyOydyTCjXB8fvcQpsYvMDdGV32MFaQsLooYegqBzvzt1jd4goWBxb6c/XQXSY/0eL1fMxl1lBkxBBxDp2snZvYr7xt2sGrt41WzuGPATdQN5vqTAeuUOArTlWEYc6vwI7UMGLa2HP6sTJxtlmFxlB+MkD2Edlk247Bt3pTWlfdrQ3xYFnSsBhhSTC3lMsLRXuxsFezBgYuQ1HEQkakFkQ8dWnHtQJtJht9xzqjUUJAx+hGuMzjYzgj3MOL36XaDS5iHgLBRvZyWj57fwLOV4UGVyQgRgTNg6+jVaA5ZGwDKk3MULkl2iOOFmR9VOvxcDoeq+PRnp4TkC+p3pxwJDm4qKJEbDkwUaJeCr9dG3CKNGOrnZH9tdSs/WYx6vypo6Iu8c0ZXlUaZmLMqdXeVO9x2axiAQxpW9SenkhdohbfuTDyCkpMlqF7ojTxUBdqzWsDs5/p9nLZ6KLtfym5A4u
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque