apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - upstream-manifests/cluster-install
  - argocd-oidc-sealed-secret.yaml
patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
    path: argocd-rbac-cm.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: cmd-params.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-notifications-cm
    path: notifications-cm.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: reposerver-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
    path: dex-security-patch.yaml
