apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-cm
    app.kubernetes.io/part-of: argocd
data:
  service.webhook.ntfy: |
    url: $ntfy-webhook-url
    headers:
      - name: Content-Type
        value: text/plain
  template.app-sync-failed: |
    webhook:
      ntfy:
        method: POST
        body: |
          Application {{.app.metadata.name}} failed to sync.
        headers:
          - name: Title
            value: "ArgoCD Sync Failed"
          - name: Tags
            value: "x"
  template.app-degraded: |
    webhook:
      ntfy:
        method: POST
        body: |
          Application {{.app.metadata.name}} is degraded.
        headers:
          - name: Title
            value: "ArgoCD Degraded"
          - name: Tags
            value: "skull"
  template.app-sync-succeeded: |
    webhook:
      ntfy:
        method: POST
        body: |
          Application {{.app.metadata.name}} has been successfully synced.
        headers:
          - name: Title
            value: "ArgoCD Synced"
          - name: Tags
            value: "tada"
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-degraded: |
    - description: Application has degraded
      send:
      - app-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
