---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haac-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${GITOPS_REPO_URL}
    targetRevision: ${GITOPS_REPO_REVISION}
    path: k8s/bootstrap/root
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
