apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy-app.yaml
  - descheduler-app.yaml
  - falco-app.yaml
  - kube-prometheus-stack-app.yaml
  - kured-app.yaml
  - litmus-app.yaml
  - loki-app.yaml
  - longhorn.yaml
  - node-feature-discovery-app.yaml
  - node-problem-detector-app.yaml
  - semaphore-app.yaml
  - trivy-operator-app.yaml
