apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    renovate/helm-chart: "litmus"
spec:
  project: platform
  source:
    repoURL: https://litmuschaos.github.io/litmus-helm/
    chart: litmus
    # renovate: registryUrl=https://litmuschaos.github.io/litmus-helm/ chart=litmus
    targetRevision: "3.28.0"
    helm:
      values: |
        existingSecret: litmus-admin-credentials
        portal:
          server:
            service:
              type: ClusterIP

        # Deploy the chaos center and agent together for homelab simplicity
        adminMode: true
        mongodb:
          architecture: replicaset
          replicaCount: 1
          arbiter:
            enabled: true
          persistence:
            storageClass: local-path
        
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
