{{- $routeNamespaces := dict -}}
{{- $autheliaNamespaces := dict -}}
{{- range $name, $conf := .Values.ingresses }}
{{- if (default true $conf.enabled) }}
{{- $namespace := $conf.namespace | default $.Release.Namespace -}}
{{- $authStrategy := "public" -}}
{{- if hasKey $conf "auth_strategy" -}}
{{- $authStrategy = ($conf.auth_strategy | toString) -}}
{{- end -}}
{{- $_ := set $routeNamespaces $namespace true -}}
{{- if eq $authStrategy "edge_forward_auth" }}
{{- $_ := set $autheliaNamespaces $namespace true -}}
{{- end }}
{{- end }}
{{- end }}
{{- range $namespace, $_ := $routeNamespaces }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: force-https
  namespace: {{ $namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
{{- if hasKey $autheliaNamespaces $namespace }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: {{ $namespace }}
spec:
  forwardAuth:
    address: http://authelia.mgmt.svc.cluster.local:9091/api/authz/forward-auth?strategy=header
    trustForwardHeader: false
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
{{- end }}
{{- end }}
