apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  gatewayClassName: {{ .Values.gateway.class }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.entryPoints.httpPort }}
      allowedRoutes:
        namespaces:
          from: All
