---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: mgmt
data:
  settings.yaml: |
{{ include "haac-stack.homepage.settings" . | indent 4 }}
  services.yaml: |
{{ include "haac-stack.homepage.services" . | indent 4 }}
  widgets.yaml: |
{{ include "haac-stack.homepage.widgets" . | indent 4 }}
  bookmarks.yaml: |
{{ include "haac-stack.homepage.bookmarks" . | indent 4 }}
