# Intel GPU Device Plugin daemonset - needed to expose Intel iGPU to Kubernetes pods
# This runs only on nodes discovered by Node Feature Discovery.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
# {{- range .Values.global.scheduling.gpu.intelNodeFeatureLabels }}
              - matchExpressions:
                  - key: "{{ . }}"
                    operator: In
                    values: ["true"]
# {{- end }}
      initContainers:
        - name: init-driver
          image: >-
            {{ .Values.global.images.intelGpuInit.repository }}:{{ .Values.global.images.intelGpuInit.tag }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/kubernetes/node-feature-discovery/source.d
              name: nfd-features
      containers:
        - name: intel-gpu-plugin
          image: >-
            {{ .Values.global.images.intelGpuPlugin.repository }}:{{ .Values.global.images.intelGpuPlugin.tag }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /dev/dri
              name: dri
            - mountPath: /sys/bus/pci
              name: pci
            - mountPath: /var/lib/kubelet/device-plugins
              name: device-plugins
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
        - name: pci
          hostPath:
            path: /sys/bus/pci
        - name: nfd-features
          hostPath:
            path: /etc/kubernetes/node-feature-discovery/source.d
            type: DirectoryOrCreate
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
