- name: Apply custom node labels to the node
  ansible.builtin.command: "k3s kubectl label node {{ ansible_facts['hostname'] }} {{ item.key }}={{ item.value }} --overwrite"
  vars:
    sanitized_node_labels: "{{ ((node_labels | default({})) | dict2items | rejectattr('key', 'in', ['gpu', 'gpu_model', 'gpu_nvidia', 'gpu_intel', 'gpu_nvidia_model', 'gpu_intel_model', 'gpu_type', 'haac.io/gpu-nvidia', 'haac.io/gpu-intel', 'haac.io/gpu-nvidia-model', 'haac.io/gpu-intel-model', 'haac.io/gpu-type']) | list | items2dict) }}"
  loop: "{{ sanitized_node_labels | dict2items }}"
  when: (sanitized_node_labels | length > 0)
  delegate_to: "{{ groups['k3s_master'][0] }}"
  ignore_errors: true

- name: Remove legacy GPU labels from the node
  ansible.builtin.command: >
    k3s kubectl label node {{ ansible_facts['hostname'] }}
    gpu- gpu_nvidia- gpu_intel- gpu_nvidia_model- gpu_intel_model- gpu_type-
    haac.io/gpu-nvidia- haac.io/gpu-intel- haac.io/gpu-nvidia-model- haac.io/gpu-intel-model- haac.io/gpu-type-
  when: (hostvars[proxmox_host]['has_nvidia'] | default(false)) or (hostvars[proxmox_host]['has_intel'] | default(false)) or ((node_labels | default({})) | length > 0)
  delegate_to: "{{ groups['k3s_master'][0] }}"
  ignore_errors: true
