---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-keys
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgAZREG4wlSysBuKm+K1zHYXHlOZG9kWK06uW/kYZ926jedOi+hPc2AFXt0lfGN1Mh7TC4TDt0YswQaKyuDDuCUHxOXCPhTaTWHFvc7T8KdFk9dBsb/LU++rB7WjhMi1IAQllknzsVd+FR6TPA3QYYyRcbIokEk49FJTqSRRQ+1Qw3CGcr7Fbb1MBoOyxQNsqBl3253CIJg4qfYWgNRlnll4IC8wHpV9fYWxsUJvdlgxhMve4xr8SA7upxUDylTPGpo8abGVDneVpdDuymeJKcCBO/OxNTWaQMe6oUeNIApnyZdbKn4HBqMdDblXBJtDqZRukFrV74KyBlTG/xVnCgOJauiRmSay2RFpUV8P9LhBRXMSeF+xblgfHc0KvMMB754PjffdNzOI1ORNmlCyhTTgGRVRFJ16SBRKJzwVosXhgR28WCzcxTz7XWZWvvyLf64AAiVm6tDcKNmlkL2Gy7gKpAFoqp896dB5KrfYmf070cJgWjVQZzyyc3E1Y0uRVbB5NcPlGj+iWu8h5NisFVivT1NBBqm//CFIHrGdaWwuYOeuI82i1KP6WKYCWo1bKUew+jO40IAOxUGnJ3loFwhyuKPjtPAzvq7/0Cs2dgSCsr2vnhe39/HiqP8w69T39KGXyoA6uWz3x0edofLBAb6zFnRPbZtW2z40GX61Wn/eREXqnMk07slMJfyutF5+uXVlV6i3UtmwCF83ZCwpLy0w2hlAUsJO87UVF/8+ZnSzUAFvD+biSba4Di+X
  template:
    metadata:
      name: crowdsec-keys
      namespace: crowdsec
    type: Opaque
