---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-keys
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgBzJIQkSCqA7lEilVYik9TCAguJi9I0cuEjFSPIdniGsdE5QnRMJtAmWxa7GgE/x6+yrlqKUrqU+Z3Jb74ho5hyiJB/yH9W9BO8qftuPFyv7caQrdZxKm9wZKB+NyWah/uKMPHbuP9kzpq/zEfa9bed6/ztzOcg/AbCbR5M2o166lY3QEj+qNF1rXlHl3d/EyBBIacqNfmpKAkt+QaHh6u+4Sun+P664dTfS1NJLUvBj4eBrFqR8PfDS9NZc3wY0ajrqpT/JtZE9ZabkuGpvbPCTXKyp49JSNjEvCld/2c2eR28sw/W0XaE5ybcpKiNnO2aawQNuFFqxecawyycdnBAtH64ZQkyhdVT532cq9RFP+LtxNtNagebE+EQ95Q7wRMa3lJkVGPkdFzgaQX4bVnf+ntpYdedoUQQExPnp2G8p5wLnPNf+tMHd1gCccIiCXS1qwh8/gAo2Kkg07v2MvlRHx/VPBVF3vui1kCzzFhVFYAJsdETvAfxB0EFtl/VC0OGFu4Tp08K0SY+Wow3lbjZNKu3E4/AQY6KlfRFQbVQ/MjY9yJMWBcmgU3V7ovFapw/ln8xp4npz3eBqQp6piPQ3yTw7cXiGAcReXAJCrWG75EUqVGwjJHhhu34pgw6tAVY7li5OFT3cgK2+OKSPROFUCI72vo5VjK3WTX/WNva72j/RzSCxdAF9ZF+BnuFa5H1jcj6CxyNdqNIUiif0rQsSmIVZstvTpYTf5R0f5tGCG967uc7zS1dRqGT
  template:
    metadata:
      name: crowdsec-keys
      namespace: crowdsec
    type: Opaque