---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-web-ui-auth
  namespace: crowdsec
spec:
  encryptedData:
    CROWDSEC_PASSWORD: AgCQ+xD4OmguUxHFSuRvnAhfJeXGs5D4RunTyAa/+4y4cs1kHMGAdwo7cnXoIQtemREzkR42I3jpfSid+KQ+exm+c2mC+7itomW7dchyWla9qFk+g7SZnOpLvk+ok0uzb8QUO5GWGJIJcp1yri7TgDWv5dk2dxKlg1usEj7J6GVD8BNVA8Tno5GwYazS6ug2v3lWcZNeGcrBla/1KqHJD4sbzhQKx6vve8an36e+d+XuMF7MSF+VLrrBk3WYt/KEVMzfTc3DjPOsLPGyJHHOk0amUnkaY72mnyu+ey+5XUsWzsXSWJ+sNMA+SazLhFESgeRupZku8jI32VJ9RR67mCLkpsAFEOqvpA8K16O1Fdms8I0AFx1//GJUcJqjWQF+Rgk63pyGl2IJiA1KXa7TpCDbHTmJsN4DALStjfcRqOhdB956wz3NEn+ODv6F5OgXtM9rpWB9DiCWRJSzepgO7uKgzRcMNIYHeguisoseda6Wd+o20HWxtCBwTe5VaoXQ1STHu+s94+/9/g/WRNQB8ixrMaVEYxudgfQaGWIBuxl79HC8RJ4g+DDjAEnQz7pgIhYZiK+3s7vhypOro6r5tjz92qL+WJrxb5c3l+tyxOHEDaxug+L9ibgzqb36Y/9n1xaqxxD1bti/6oR4h/czo7WVC6gKxgEYkymZk0aivfbY1NviJljU2SpjMW8C2qPpZYdVE0x9HjUqulPP0mvHWNruhTK47z21MyOoy/yVAjxVwTaBKAdnO9j3ZITH9nTe+4T8gNj5/2ceQ2XqHHPvg6pi
    CROWDSEC_USER: AgCoUBS/mdzwW0n7f8BPXnonEApD+1o4a8Qps5uFznbgL8w7qG7WvS0eYnxyW0ya7RtMf33vxYSVyAE2cI7ElAY4QjZKoOEBeY09KBJ2BwI3ntaZxScP7fnY3glIo53ZNqVsabAij3aevPHXxdOYeQr5n4H/bjoG2h3r7SPNJnOH7npKAOBiOv3DAAV10zm7q2iLi6FFJ5l6xoU+s8B/WAUvOuoHvvsdwR3tMtJOBK0Kx6R/VGj3jdtZxrgKD9OhrOUtdXXDHphMIQRKzZ69rIA/Kdgbvbk/T38/QmyQM5ed5i1iOm5/RU9U8qdTV22nfTU92fnIHMImVgKtvGhtyYijL/nYovboPFZyXBS5zuBgQtkBJkLy4pPWdCAJKl1M9a2kRi9mYJLZomQxZIJ+/uQgm+QZE5fLWC4blG+bbJUAdp/ZrjIyiazT4iKolXE34D+MWxIeb1sBLcskDX7lgBj8CdKkBpCey1crhsagYpZpGXcL1yNW6Hd5/Ggar+QhWcy8davC+dU4Lui0KblS7PD0rRwsFtCDMGkSGYPhrUHNMJiL/bjkHYpAdLgOFpuYbWj+wb8l8uw6NOkM83U+MnbRpK9WfElgRn1Y++em23f1j29deo9BedWLy4lMBbat0jW0f7mH8RrOxk7q1Am/NBBh9+MxlxdXsxnIwBk1EhrRC0shVS4AMyBr4DYFhaNO+/ajSRnWRHKEWZYF7fOy6Jc=
  template:
    metadata:
      name: crowdsec-web-ui-auth
      namespace: crowdsec
    type: Opaque
