---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-web-ui-auth
  namespace: crowdsec
spec:
  encryptedData:
    CROWDSEC_PASSWORD: AgBDwbz1IUuJVt/qOZIud2+ZQM/OjUsoAOt18JyECZFAQ1/DcesSdb4aUBXt04FsTWf2k9I0LtEC1jZ6yX81IjKNLxzy/WjrdoG2wp7rqID81usrBuXCyKvZVDW1/cUhd7G4PXTHAvgxV2h7LKVjl5WovEFtbWQsDb0ON9zpiflEpSAYR1kw6ZhoR7MiarlvR4mB3O9NW0JLZs0sBLRQF3F8srdz3v80/9mJZvOQR8obHw5mIrvgwRtUGjcS/tjPTlOPIihCfwYCpzPxsPvUl1thLzZVe2OxYijH/5IMdekkh/YwuTOldJkBaYuWjDHUai4iT0gkftjOXLblzuq4iFiBJbJnMyVApR3iTHGiPRsey6P8QxhqliwFeYVh4X2N6+nIp7cN0cBZlcENV3VCcgNtNUnhqI83KJdwxrqUfc1/UWOoTq+4vA5iOZC0im/At/IFRWy+ddZIHdq/eeQBi2o+Z7FEPy2ArDf25tm2KsOkdzYylIVCgT9u/ngL2RSXY9z7hhmO+dY9aAmhE0Tz6Diq6mfCUY8vRDUHKy1n55v4oGYq0Gepn/kiFs71PjVvL/+GuvKBL17YwqIcYxBI15dudRcphGX9rFL4xNa4M7EYUYoljYs4CZQJKzjz64esz9MohAZHSPvBbxYqCvMbPAipKH1ackzX41UiCFs655NTnTTxxZee2kTboWRD0zU/J+qLxChFGzllZuH+VaUx2FOfVFtIWDbXWKQF2DG4eNWj+MPIfWFuCxA6V7fjD04Kf6q4JMcIw59y5QNbYZFne1dI
    CROWDSEC_USER: AgCQojJhDW4Yg67jBa2KLTjK4/Dm46n/9LFlSLT1fxrDOi5NDkBH5mJp+a9dV8OQQmZtIxCOmwsm3xjJgjGY5LLOYktpnLRSPcw7XPksyVedWP1Fyvu1d9P/ntTqI7rqAup5g+yoxcUgmoAmGlNkM67qlVlHYXd6hM5M91q82rbvwbL3ApQs58LwE/ILbeLXhqlVkJXrLsAc2mkLm8IjZayEiBFMmeexErkwVGm7q1im7AEMSI0YJVDeYRBGOFfRKy+47BEZYA/klyIYwXw7FBld0XddpB0oZkSrI27MNxrCrT5LIFb9ImpSovZ1AQcPA9DBCf0A3De+KlhFLJekoK8ATF21wHiWssrgLLvJEycFroqWY7YUSz13mc9GjXP9L0cplmDLVSg7PXijrwyDqeeV3MUiPmCV5jzM3eQ7CEFPNjHXxz8V0e3OYKYobWAh/iLEH50fYa2OzWOCnEK7H/rYtuiGJU3lysMI5pAEcW3XmLJQvaW6zyRKuQqrblgH7CfcBj/Igksm8u5+VpcvkCBmDRpGXp3/scvrDp4YtZbo4Ic4rM3YL2+wye2Ic9iEhyc7ewoyxHIpo4w5YkaDghWwMvl3EJwrz48M1RMedscD3f7OUNyVexTizzSd2i2nyJBA0trAJ5m6bmA7A+0sD7owao0jwSxMOGVjfyN3ugNno1ajEeFLqbODUbPzBgTT9MwtTI4UkRIpvx8uW6HY/3U=
  template:
    metadata:
      name: crowdsec-web-ui-auth
      namespace: crowdsec
    type: Opaque
