---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-web-ui-auth
  namespace: crowdsec
spec:
  encryptedData:
    CROWDSEC_PASSWORD: AgARBhA64W0BdGVj1ZIC+h5TiQ9kTohSfcmliwCWjwUOTJEPJ3CCQgmX6wQIAZLJkRAi4M05nY6ylEKSUKbuiSUp6AVfYJQBlH18ttF8BUsqIo1as+iruEO++dLlVHDiwqDp+o2YP9MQ6bRnJscGfwcKnTBo/np9lNng7zg0VPQfeJa2uAdvmPsixrX4xyqsDMUVyBWqq0+O4sWkGcrYJcxuz3rXDY5slcemdaGlr/noKEt/ADp65wq38pWZP3h5oa6RTAzFnfeTnXDhbTbOvbYXy7Gu9UkQIp+e4HcDHLVIgDzFk9cKY7Dg7s0Dp67QsQKDiY40bmYYhT5Hp3/fkGA+YSJH/DtqqS2dpmXoV0vy5vEi+RJCKOuYRfX6w65Cp8Q14OXIUbOZDFvqeT0O4kye5VsJyj18/J7Eik5b3HV5HZLPvYlBlIOzjZgJsHe9eCmC6T89MwdZCoXMlT5bAF4gMtfBhK/LGgoFOD3Hc8LJSkehpFS9yvoEUvJmPccasNho3HWCNq80j7/Fb/wxR2/A8j6PcMWSmt9ACNGL2h1+hM7HWC2E5/3iu7mwvA6wfUctxSXzhyVIvodn7oLStVItdBt8T0TJXSpmG0OnMFYkWABwxiIwIJREwPHXKtRwyrNwz+YS8F49Z24AWOUx+YVonUdv/VkcZ2W0jS4BFkQKwv5/DdTkS3SicW5YvuzuITW/ivds9lNCmWZ1IhdLN17sFM+tlhpsLD3Nfqf3xbRA7tOXDILdL9BRfeAAUUh0jvB4RKMgjEPs7HIfCCJkMvm8
    CROWDSEC_USER: AgBBlz2hUtcIm4qi16dzHjeZp6uyxi1IlY3m2tsAeUnbgpA0BVeimHLSFn9MrJY0Wh6rjYdVhgexvXkNynrktHRNhfsUbhocm6pvumOjWkzpgt2HTLnZ8TLl3dN1WRJHDGM533zRlnALWuA1iRFbNENvEEqUtyWEObXh9P1XW8Zn8melaD2Se734ijLSamgZNBTJZ9P58xq6OeQoelcsnzVa8sdIAcAEz2p2m6uYadUEJ+MuNdF+PQb1lM8NBTVyn4lLjzWb/athZfOknekk+CHAaJslLfYYB8ZxTFtX/da9J2o8oZJ3FKXZvZzSplMVGmpTMHFQa0QxIAhpmtiI97VVrPITIR6ewa2u72x2vx6vMPHpwf+/xeqIqttSWL/g5H/QUtXpdoPLkXuUeG8y+KqZ/wTouss6ex7SGOYevi5K/nwnd2FaHyURtAXR7vUFVWfIWkB2kVlOqcQqZJi4gU1ovvaYNp223dNcad6QumC9hv0G6EnBJ9b3N6W6AY6bIqMZt5HrABC3+q34bvAsUhJOdFc8Rb8Kq6igKo1mdugUARcFfQuzFs0ee614/lcdepxRsj61BurNK/4KEzMgGNIemRFqyT93W6B/ZlAUcsBefQXjRpwaEQHF8YNUBbfauORN5K4taPMJperhgEOmq+/vG6x9y3G0nGK/o4mecPsRgw+9+f6QCgbLaKkES6dTIolHlLRNFSLjMOA4N/t4uIk=
  template:
    metadata:
      name: crowdsec-web-ui-auth
      namespace: crowdsec
    type: Opaque
