---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-keys
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgBtaeNfkL/CEgiAcc2yPNPlJDHeeOfZ8fCYUDRBn/nt0vLhltTeW3/aUVAcM/nXIc6q9Q1jhA2ppsGeceAH+GZrDn/wnPhGRtzO1CG48Oy+pXoUiwogSYfXuiB7E6UnDGOJQNNyLikn8N/dNBgCDgfwOlDbqZa8DjkLoClaw7YgJf+3mlhfQug8DS78VkK+ed8kyLwJwQR+AaTOf42dS/9+cJY8TH4a6RGrN4vtE5Gx4itTTtUFAtdBaY39n+qTfDTn7agK2FCM/UpJ1DjSbKrWCumWezbCgsyy10VzQ1KGJDlEgJBtW66sVaGXExqGq3VORRtq2POSgGn8b1WkaxAe3wEn0VYfA0HJvRk2fJ1GHqx8wXmBjG+M8sfhMfKpbJ7QdrIna8hUNtX1X7oYrjokVOsaIlUlMjB+7GRctc1LF5097kMtQokv6Ed11rhC+5f+54i66V4osgPSSDRsTzoA8IJt8G42T+yy8uR4Rmsl9KrD2eu1/fu1s9L5DrutVKbRm2fu1eKxYkAqt4MRBEacykSqQW1+qjM4PA8pC8E93EmBwEOA5ie9FB/nPg7Hpv4POlbw0/t//P5GYbBdz68+8IpQf5LIPhmgqk3jL531HWdqjJFMM0PxjyOwQObJLdrAyKCHFHNjjZ4OknhYoPkSdymBmhYgSHhdilDilJWVyYkRfbsStScwIZV0kgyA6WfcubgJAk8ojsMytZULo83EB/nQ2Ev7d2b6SFRFUDsGGHCzxjbgdVYTqHOy
  template:
    metadata:
      name: crowdsec-keys
      namespace: crowdsec
    type: Opaque