---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
  namespace: mgmt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:v2.17.0
          command:
            - ntfy
            - serve
          env:
            - name: NTFY_BASE_URL
              value: "https://ntfy.{{ .Values.global.domainName }}"
            - name: NTFY_CACHE_FILE
              value: "/var/cache/ntfy/cache.db"
            - name: NTFY_AUTH_FILE
              value: "/var/cache/ntfy/user.db"
            - name: NTFY_AUTH_DEFAULT_ACCESS
              value: "read-write"
            - name: NTFY_BEHIND_PROXY
              value: "true"
            - name: NTFY_ATTACHMENT_CACHE_DIR
              value: "/var/cache/ntfy/attachments"
            - name: NTFY_ENABLE_LOGIN
              value: "true"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/cache/ntfy
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ntfy-data
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: mgmt
spec:
  selector:
    app: ntfy
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: mgmt
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: mgmt-force-https@kubernetescrd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ntfy.{{ .Values.global.domainName }}`)
      kind: Rule
      services:
        - name: ntfy
          port: 80
