apiVersion: v2
name: haac-stack
description: Home as a Code (HaaC) Umbrella Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kured
    version: "5.5.1"
    repository: https://kubereboot.github.io/charts
  - name: node-problem-detector
    version: "2.3.13"
    repository: https://charts.deliveryhero.io
