global:
  domainName: "nucleoautogenerativo.it"

storage:
  uid: "13000"
  gid: "13000"

vpn:
  serverCountries: "Netherlands"
  podSubnet: "10.42.0.0/16,192.168.0.0/24,100.64.0.0/10"
  svcSubnet: "10.43.0.0/16"
  dnsIp: "10.43.0.10"

qui:
  username: "admin"

longhorn:
  defaultSettings:
    # NAS is mounted natively into the Proxmox nodes (and thus LXC/K3s) at HOST_NAS_PATH
    backupTarget: "file:///mnt/pve/zima/longhorn-backups"
    backupTargetCredentialSecret: ""
    # Create a default recurring job that runs daily at 2:00 AM
  persistence:
    defaultClassReplicaCount: 2
  recurringJobSelector:
    enable: true
    jobList: |
      [
        {"name":"daily-backup", "task":"backup", "cron":"0 2 * * *", "retain":7}
      ]
