global:
  domainName: "nucleoautogenerativo.it"

storage:
  uid: "13000"
  gid: "13000"

vpn:
  serverCountries: "Netherlands"

qui:
  username: "admin"

# Kured subchart values
kured:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  configuration:
    period: 1h
    rebootSentinelFile: /var/run/reboot-required
    startTime: "01:00"
    endTime: "05:00"
    timeZone: Europe/Rome
    rebootDays: [mon, tue, wed, thu, fri, sat, sun]
    drainGracePeriod: 120s
    skipWaitForDeleteTimeoutSeconds: 60
    notifyUrl: "generic+http://ntfy.mgmt.svc.cluster.local:80/haac_alerts?title=Kured+Reboot&tags=arrows_counterclockwise"
  securityContext:
    privileged: true
  hostPID: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

# Node Problem Detector subchart values
node-problem-detector:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  securityContext:
    privileged: true
  env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
