apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.nucleoautogenerativo.it
  # Enable OIDC
  oidc.config: |
    name: Authelia
    issuer: https://auth.nucleoautogenerativo.it
    clientID: argocd
    clientSecret: $argocd-sso-secret:client_secret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
