---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2  # Run 2 replicas for HA
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: cloudflared
          image: "{{ .Values.global.images.cloudflared.repository }}:{{ .Values.global.images.cloudflared.tag }}"
          args:
            - tunnel
            - --no-autoupdate
            - --protocol
            - http2
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-token
                  key: token
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
