apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd
  - applications
  - crowdsec/crowdsec-lapi-sealed-secret.yaml
  - chaos/litmus-admin-credentials-sealed-secret.yaml
  - chaos/litmus-mongodb-credentials-sealed-secret.yaml
  - falco-ingest-service.yaml
  - observability
  - traefik/crowdsec-bouncer-sealed-secret.yaml
  - traefik/traefik-gateway-rbac.yaml
  - traefik/traefik-gatewayclass.yaml
  - traefik/traefik-config.yaml
