apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd
  - applications
  - traefik/traefik-gateway-rbac.yaml
  - traefik/traefik-gatewayclass.yaml
  - traefik/traefik-config.yaml
