apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-latest-tag.yaml
  - disallow-privilege-escalation.yaml
  - disallow-privileged-containers.yaml
  - require-pod-requests-limits.yaml
  - require-run-as-nonroot.yaml
